C
C SECOND-ORDER TETRAHEDRON (10 NODES): C3D10
C
      SUBROUTINE UEL(RHS,AMATRX,SVARS,ENERGY,NDOFEL,NRHS,NSVARS,
     1 PROPS,NPROPS,COORDS,MCRD,NNODE,U,DU,V,A,JTYPE,TIME,DTIME,
     2 KSTEP,KINC,JELEM,PARAMS,NDLOAD,JDLTYP,ADLMAG,PREDEF,
     3 NPREDF,LFLAGS,MLVARX,DDLMAG,MDLOAD,PNEWDT,JPROPS,NJPROP,
     4 PERIOD)
C
C      INCLUDE 'ABA_PARAM.INC'
      IMPLICIT NONE
C
      INTEGER NSVARS,NDI,NSHR,NTENS,IPN,IP,I,K1,K2,N1,N2,NSTATV,
     1 NSTATINT,I2,NSTATSTRAIN,NSTATSTRESS,NPROPS,KSTEP,KINC,
     2 K3,NDOFEL,NRHS,MCRD,NNODE,JTYPE,JELEM,NDLOAD,NPREDF,MLVARX,
     3 NJPROP,MDLOAD,J,I1,LFLAGS(*),PLOTFLAG,NSTATORIENT,NSTATSTRESSGC

      DOUBLE PRECISION RHS(MLVARX,*),AMATRX(NDOFEL,NDOFEL),PROPS(*),
     1 SVARS(NSVARS),ENERGY(8),COORDS(MCRD,NNODE),U(NDOFEL),
     2 DU(MLVARX,*),V(NDOFEL),A(NDOFEL),TIME(2),PARAMS(*),
     3 JDLTYP(MDLOAD,*),ADLMAG(MDLOAD,*),DDLMAG(MDLOAD,*),
     4 PREDEF(2,NPREDF,NNODE),JPROPS(*),UV(30),UVNL(4),DUVNL(4)
C 
      DOUBLE PRECISION X(NNODE),Y(NNODE),Z(NNODE),X0(NNODE),Y0(NNODE),
     1 Z0(NNODE),X1(NNODE),Y1(NNODE),Z1(NNODE),X2(NNODE),Y2(NNODE),
     2 Z2(NNODE),GAUSS(2),W(4),KSI(4),ETA(4),ZETA(4),JJ(3,3),
     3 DNZETA(NNODE),ID(3,3),DNKSI(NNODE),J0(3,3),B(6,30),J2(3,3),
     4 BC(6,30),BC2(9,30),BC2T(30,9),STREXPND(9,9),BCTSTR1(30,9),
     5 BC1(9,30),BC1T(30,9),BCTSTR2(30,9)
C
      DOUBLE PRECISION DNX(NNODE),DNY(NNODE),DNZ(NNODE),DNX0(NNODE),
     1 DNY0(NNODE),DNZ0(NNODE),BS(9,30),DSPINV(9),DSPIN(3,3),
     2 DNNLX(4),BTSEFN(30,4),
     3 DNNLY(4),DNNLZ(4),BNL(3,4),BNLT(4,3),NNL(1,4),NNLT(4,1),
     4 DNX2(NNODE),DNY2(NNODE),DNZ2(NNODE),DNNLX2(4),DNNLY2(4),
     5 DNNLZ2(4),BNLC(3,4)
C
      DOUBLE PRECISION DFGRD1(3,3),DSTRAN(6),DFGRD0(3,3),DNETA(NNODE),
     1 DDSDDE(6,6),BT(30,6),XK11(30,30),XK11M(30,30),
     2 DSPINHL(3,3),IDSPINHL(3,3),NIDSPINHL(3,3),NIDSPINHLINV(3,3),
     3 DROT(3,3),STRAN(6),BTC(30,6),BTCB(30,30),DUV(30),STRESS(6),
     4 RHSV(NDOFEL),KAPPABARN(4,1),BTSEFF(30,1),XK12(30,4)
C
      DOUBLE PRECISION ZERO, ONE, TWO, THREE, FOUR, SIX, EIGHT,DETJ,
     1 HALF,DTIME,PNEWDT,PERIOD,DETJ0,DETF1,XEVOL,XM,XL,KAPPABAR,
     2 XMDKDETJ,XL2,KHAT1,DETXAO,DETXA,DETXBO,DETXB,XAT(3,3),
     3 XBT(3,3),J2NLINV(3,3),DETJ2,BETA(3,10),XK11G1(30,30),
     4 XK11G2(30,30),XH(10,10)
C
      DOUBLE PRECISION JINV(3,3),J0INV(3,3),J2INV(3,3),
     1 NNLTDK(4,6), XK21(4,30),BNLTBNL(4,4),XLBNLTBNL(4,4),
     2 XK22(4,4),NNLTNNL(4,4),NNLTNNLDK(4,1),XLBNLTBNLDK(4,1),
     3 XKNNLT(4,1),FNL(4,1),FNL1(4,1),JJNL(3,3),JNLINV(3,3),
     4 NNLTDKB(4,30),NTNLBTB(4,4),AA0(3),BB0(3),CC0(3),J2NL(3,3)
     
      DOUBLE PRECISION DNNLKSI(4), DNNLETA(4), DNNLZETA(4), 
     1 DROTT(3,3),DFGRD01(3,3),XA(3,3),STRESSOLD(6),
     2 DSTRANGC(6),AA(3),BB(3),DSTRESS(6), DSTRESSLC(6),
     3 CC(3),DROT2(3,3),XB(3,3),AA1(3),BB1(3),CC1(3),DETJNL,
     4 STRESST(3,3),XBO(3,3),XAO(3,3),DDSDDER(6,6),STRESSR(6) 
C     
       DOUBLE PRECISION IWLIHL(3,3),IWRTIHRT(3,3),SEFFIWRTIHRT(3,3),
     1 IWLIHRT(3,3),IWRTIHL(3,3),SEFFIWRTIHL(3,3),SEFFIWLIHL(3,3),
     2 SEFFIWLIHRT(3,3),SSEFFTENSOR(3,3),DSTRANTENSOR(3,3),
     3 DSTRANIWHL(3,3), DSTRANIWHLIHL(3,3),IWHRTIHRT(3,3),
     4 DSTRANIWHLIHRT(3,3),IWHRTIHL(3,3)
C
      DOUBLE PRECISION H1(3,3,3,3),H2(3,3,3,3),H3(3,3,3,3),
     1 WR1(3,3,3,3),WR2(3,3,3,3),WWWWR(3,3,3,3),WL1(3,3,3,3),
     2 WWWWL(3,3,3,3),AAK(3,3),AAKT(3,3),SA1(3,3,3,3),SA2(3,3,3,3),
     3 TANGDENSTENSOR(3,3,3,3),DDSDDETENSOR(3,3,3,3),SSSSA(3,3,3,3),
     4 HHHH(3,3,3,3),WL2(3,3,3,3)       
C
C     INTERFACE WITH NONLOCAL UMAT
      DOUBLE PRECISION DKDE1(1,6),SSEFF1(6,1),DKDE(6),DKDER(6),
     1 DDDK,SSEFF(6),SSEFFR(6),KAPPA1
C      
C     FOR DEBUGGING
      DOUBLE PRECISION KAPPA4,DKAPPA,CONDNO,DKDD(1,30),KAPPA5,
     1  UABA(30),K21JAC(4,30),RELVOL,BVTV,DETJ2NL
C
      PARAMETER(ZERO=0.D0,ONE=1.D0,TWO=2.D0,THREE=3.D0,FOUR=4.D0,
     1 SIX=6.D0,EIGHT=8.D0,HALF=0.5D0,NDI=3,NSHR=3,IPN=4)
C
      DOUBLE PRECISION STATEV(NSVARS/IPN-(NDI+NSHR)-9) 
C
C     TOTAL NUMBER OF STRESS OR STRAIN COMPONENTS
C
      NTENS=NDI+NSHR
C
C     TOTAL NUMBER OF STATE VARIABLES FOR EACH INTEGRATION POINT (NSTATINT)
C     NUMBER OF STATE VARIABLES FOR EACH INTEGRATION POINT FOR UMAT (NSTATV)
C     THE REST IS RESERVED FOR STRAIN AND STRESS TENSORS
C
      NSTATINT=NSVARS/IPN
      NSTATV=NSVARS/IPN-(NDI+NSHR)-9
C     
C      DATA GAUSS/0.138196601125011, 0.585410196624969/
      GAUSS(1) = (5.0D0-DSQRT(5.0D0))/20.0D0
      GAUSS(2) = (5.0D0+3.0D0*DSQRT(5.0D0))/20.0D0 
C
C     XM: NONLOCAL WEIGHT
C     XL: NONLOCAL LENGTH SCALE
C      
      XM = PROPS(5)
C
      IF(KSTEP .EQ. 1 .AND. KINC .EQ. 1) THEN
      DO I=1, NSVARS
      SVARS(I) = ZERO
      END DO
      END IF
      
      DO I=1,NDOFEL
      RHS(NDOFEL,1)=ZERO
      END DO
      
      RHSV=ZERO
      DUV=ZERO
      UV=ZERO
      
      XK11=ZERO
      XK11M=ZERO
      XK11G1=ZERO
      XK12=ZERO
      XK21=ZERO
      XK22=ZERO
      XH=ZERO
      
      AMATRX=ZERO

      IP = 0
C      
C     AXES OF THE LOCAL COORDINATE SYSTEM IN THE UNDEFORMED CONFIGURATION
C
C      AA0 = ZERO
C      BB0 = ZERO
C      CC0 = ZERO
      
      AA0(1) = PROPS(10)
      AA0(2) = PROPS(11)
      AA0(3) = PROPS(12)
      
      BB0(1) = PROPS(13)
      BB0(2) = PROPS(14)
      BB0(3) = PROPS(15)
      
      CC0(1) = (AA0(2)*BB0(3)-AA0(3)*BB0(2))
      CC0(2) = (AA0(3)*BB0(1)-AA0(1)*BB0(3))
      CC0(3) = (AA0(1)*BB0(2)-AA0(2)*BB0(1))
C      
C     AXES OF THE LOCAL COORDINATE SYSTEM IN THE DEFORMED CONFIGURATION
C
      AA  = ZERO
      BB  = ZERO
      CC  = ZERO
      
      XA = ZERO
      XAO = ZERO
      XB = ZERO
      XBO = ZERO
C
C BEGINNING OF THE LOOP OVER INTEGRATION POINTS   
C
      DO IP=1,IPN
C
C INITIALIZE RIGHT-HAND-SIDE (RHS) AND ELEMENT STIFFNESS MATRIX (AMATRX)
C      
      PLOTFLAG = 0
      KAPPABARN=ZERO
      KAPPABAR=ZERO
      KHAT1=ZERO
      B=ZERO
      BC=ZERO
      BC1=ZERO
      BC1T=ZERO
      BC2=ZERO
      BC2T=ZERO
      BCTSTR1=ZERO
      BCTSTR2=ZERO
      BS=ZERO
      STREXPND=ZERO
      DNNLKSI=ZERO
      DNNLETA=ZERO
      DNNLZETA=ZERO
      XLBNLTBNL=ZERO
      XLBNLTBNLDK=ZERO
      DUV=ZERO
      DUVNL=ZERO
      UVNL=ZERO
      BNL=ZERO
      BNLT=ZERO
      BNLC=ZERO
      NNLTDK=ZERO
      NNLTDKB=ZERO
      BNLTBNL=ZERO
      XL2=ZERO
      NTNLBTB=ZERO
      DETJ=ZERO
      BTCB=ZERO
      BT=ZERO
      BTSEFF=ZERO
      NNL=ZERO
      BTSEFN=ZERO
      XMDKDETJ=ZERO
      NNLT=ZERO
      NNLTNNL=ZERO
      NNLTNNLDK=ZERO
      XKNNLT=ZERO      
      W=ZERO
      KAPPA1=ZERO
      FNL1=ZERO
      FNL=ZERO     
      DKDE = ZERO
      DKDE1 = ZERO
      DKDER = ZERO
      SSEFF = ZERO
      SSEFF1 = ZERO
      SSEFFR = ZERO
      DDSDDE = ZERO
      DDSDDER = ZERO
      DROT = ZERO
      DROTT = ZERO
      STRESS = ZERO
      DSTRESSLC = ZERO
      DSTRESS = ZERO
      STRESSR = ZERO
      RELVOL = ZERO
      
      H1 = ZERO
      H2 = ZERO
      H3 = ZERO
      HHHH = ZERO

      WR1 = ZERO
      WR2 = ZERO
      WWWWR = ZERO

      WL1 = ZERO
      WL2 = ZERO
      WWWWL = ZERO
      
      AAK = ZERO
      AAKT = ZERO

      SA1 = ZERO
      SA2 = ZERO
      TANGDENSTENSOR = ZERO
      DDSDDETENSOR = ZERO
      SSSSA = ZERO      

      DUV(1)=DU(1,1)
      DUV(2)=DU(2,1)
      DUV(3)=DU(3,1)
      
      DUV(4)=DU(4,1)
      DUV(5)=DU(5,1)
      DUV(6)=DU(6,1)
      
      
      DUV(7)=DU(7,1)
      DUV(8)=DU(8,1)
      DUV(9)=DU(9,1)
      
      DUV(10)=DU(10,1)
      DUV(11)=DU(11,1)
      DUV(12)=DU(12,1)
      
      DUV(13)=DU(13,1)
      DUV(14)=DU(14,1)
      DUV(15)=DU(15,1)
      
      DUV(16)=DU(16,1)
      DUV(17)=DU(17,1)
      DUV(18)=DU(18,1)
      
      DUV(19)=DU(19,1)
      DUV(20)=DU(20,1)
      DUV(21)=DU(21,1)
      
      DUV(22)=DU(22,1)
      DUV(23)=DU(23,1)
      DUV(24)=DU(24,1)
      
      DUV(25)=DU(25,1)
      DUV(26)=DU(26,1)
      DUV(27)=DU(27,1)
      
      DUV(28)=DU(28,1)
      DUV(29)=DU(29,1)
      DUV(30)=DU(30,1) 
         
      DUVNL(1)=DU(31,1)
      DUVNL(2)=DU(32,1)
      DUVNL(3)=DU(33,1)
      DUVNL(4)=DU(34,1)
C
      UV(1)=U(1)
      UV(2)=U(2)
      UV(3)=U(3)
      
      UV(4)=U(4)
      UV(5)=U(5)
      UV(6)=U(6)

      UV(7)=U(7)
      UV(8)=U(8)
      UV(9)=U(9)
      
      UV(10)=U(10)
      UV(11)=U(11)
      UV(12)=U(12)
      
      UV(13)=U(13)
      UV(14)=U(14)
      UV(15)=U(15)
      
      UV(16)=U(16)
      UV(17)=U(17)
      UV(18)=U(18)
      
      UV(19)=U(19)
      UV(20)=U(20)
      UV(21)=U(21)
      
      UV(22)=U(22)
      UV(23)=U(23)
      UV(24)=U(24)
      
      UV(25)=U(25)
      UV(26)=U(26)
      UV(27)=U(27)
      
      UV(28)=U(28)
      UV(29)=U(29)
      UV(30)=U(30)
      
      UVNL(1)=U(31)
      UVNL(2)=U(32)
      UVNL(3)=U(33)
      UVNL(4)=U(34)
C
C SET UP IDENTITY TENSOR
C
      ID(1,1)=ONE
      ID(1,2)=ZERO
      ID(1,3)=ZERO
      ID(2,1)=ZERO
      ID(2,2)=ONE
      ID(2,3)=ZERO
      ID(3,1)=ZERO
      ID(3,2)=ZERO
      ID(3,3)=ONE
C
C SPATIAL POSITION OF THE NODES IN THE ORIGINAL CONFIGURATION
C
      DO K2=1,10
      X0(K2)=COORDS(1,K2)
      Y0(K2)=COORDS(2,K2)
      Z0(K2)=COORDS(3,K2)
      END DO 
C
C SPATIAL POSITION OF THE NODES AT THE BEGINNING OF THE CURRENT INCREMENT
C
      DO K2=1,10
      X1(K2)=COORDS(1,K2)+UV(3*K2-2)-DUV(3*K2-2)
      Y1(K2)=COORDS(2,K2)+UV(3*K2-1)-DUV(3*K2-1)
      Z1(K2)=COORDS(3,K2)+UV(3*K2)-DUV(3*K2)
      END DO  
C
C SPATIAL POSITION OF THE NODES AT THE END OF THE CURRENT INCREMENT
C
      DO K2=1,10
      X2(K2)=COORDS(1,K2)+UV(3*K2-2)
      Y2(K2)=COORDS(2,K2)+UV(3*K2-1)
      Z2(K2)=COORDS(3,K2)+UV(3*K2)
      END DO  
C
C SPATIAL POSITION OF THE NODES AT THE MIDDLE OF THE CURRENT INCREMENT
C
      DO K2=1,10
      X(K2)=COORDS(1,K2)+UV(3*K2-2)-DUV(3*K2-2)/TWO
      Y(K2)=COORDS(2,K2)+UV(3*K2-1)-DUV(3*K2-1)/TWO
      Z(K2)=COORDS(3,K2)+UV(3*K2)-DUV(3*K2)/TWO
      END DO  
C
C THE VALUES OF NODAL KAPPABAR AT THE END OF THE CURRENT INCREMENT
C
      DO K2=1,4
      KAPPABARN(K2,1) = UVNL(K2)
      END DO
C
C COORDINATES OF THE INTEGRATION POINTS
C
      KSI(1)=GAUSS(1)
      ETA(1)=GAUSS(1)
      ZETA(1)=GAUSS(1)
C
      KSI(2)=GAUSS(2)
      ETA(2)=GAUSS(1)
      ZETA(2)=GAUSS(1)
C
      KSI(3)=GAUSS(1)
      ETA(3)=GAUSS(2)
      ZETA(3)=GAUSS(1)
C
      KSI(4)=GAUSS(1)
      ETA(4)=GAUSS(1)
      ZETA(4)=GAUSS(2)
C
C WEIGHT OF EACH INTEGRATION POINT
C
      W(1)=0.25D0
      W(2)=0.25D0
      W(3)=0.25D0
      W(4)=0.25D0
C
C SHAPE FUNCTIONS:
C FROM http://www.scribd.com/doc/59724360/50/The-10-node-tetrahedral-element
C OR J. K. BATHE, SECTION 5.3 FORMULATION OF CONTINUUM ELEMENTS, PAGE 375
C ALSO ABAQUS DOCUMENTATION 3.2.6 Triangular, tetrahedral, and wedge elements
C FOR STRAIN, SPIN AND ROTATION TENSORS SEE ABAQUS DOCUMENTATION SECTION
C 3.2.2 Solid element formulation, AS WELL AS SEE FEAP THEORY MANUAL
C CHAPTER 4, PAGE 22 
C
C N1=[2*(1-KSI-ETA-ZETA)-1]*[1-KSI-ETA-ZETA]
C N2=(2*KSI-1)*KSI
C N3=(2*ETA-1)*ETA
C N4=(2*ZETA-1)*ZETA
C N5=4*(1-KSI-ETA-ZETA)*KSI
C N6=4*KSI*ETA
C N7=4*(1-KSI-ETA-ZETA)*ETA
C N8=4*(1-KSI-ETA-ZETA)*ZETA
C N9=4*KSI*ZETA
C N10=4*ETA*ZETA
C
C THE SHAPE FUNCTIONS FOR THE NONLOCAL VARIABLE:
C
      NNL(1,1) = ONE-KSI(IP)-ETA(IP)-ZETA(IP)
      NNL(1,2) = KSI(IP)
      NNL(1,3) = ETA(IP)
      NNL(1,4) = ZETA(IP)
      
C      CALL KMATTRANS2(NNL,NNLT,1,4)
      NNLT = TRANSPOSE(NNL)
      
      KAPPABAR = ZERO
      
      KAPPABAR = NNL(1,1)*KAPPABARN(1,1)+NNL(1,2)*KAPPABARN(2,1)+
     1           NNL(1,3)*KAPPABARN(3,1)+NNL(1,4)*KAPPABARN(4,1)
C
      IF(KAPPABAR .LT. ZERO) THEN
      KAPPABAR = ZERO
      END IF
C 
C     LOCAL DIFFERENTIATION OF SHAPE FUNCTIONS (DN/DKSI)
C
      DNKSI(1)=ONE-FOUR*(ONE-KSI(IP)-ETA(IP)-ZETA(IP))
      DNETA(1)=ONE-FOUR*(ONE-KSI(IP)-ETA(IP)-ZETA(IP))
      DNZETA(1)=ONE-FOUR*(ONE-KSI(IP)-ETA(IP)-ZETA(IP))

      DNKSI(2)=-ONE+FOUR*KSI(IP)
      DNETA(2)=ZERO
      DNZETA(2)=ZERO
      
      DNKSI(3)=ZERO
      DNETA(3)=-ONE+FOUR*ETA(IP)
      DNZETA(3)=ZERO
      
      DNKSI(4)=ZERO
      DNETA(4)=ZERO
      DNZETA(4)=-ONE+FOUR*ZETA(IP)
      
      DNKSI(5)=-FOUR*KSI(IP)+FOUR*(ONE-KSI(IP)-ETA(IP)-ZETA(IP))
      DNETA(5)=-FOUR*KSI(IP)
      DNZETA(5)=-FOUR*KSI(IP)
      
      DNKSI(6)=FOUR*ETA(IP)
      DNETA(6)=FOUR*KSI(IP)
      DNZETA(6)=ZERO
      
      DNKSI(7)=-FOUR*ETA(IP)
      DNETA(7)=-FOUR*ETA(IP)+FOUR*(ONE-KSI(IP)-ETA(IP)-ZETA(IP))
      DNZETA(7)=-FOUR*ETA(IP)
      
      DNKSI(8)=-FOUR*ZETA(IP)
      DNETA(8)=-FOUR*ZETA(IP)
      DNZETA(8)=-FOUR*ZETA(IP)+FOUR*(ONE-KSI(IP)-ETA(IP)-ZETA(IP))
      
      DNKSI(9)=FOUR*ZETA(IP)
      DNETA(9)=ZERO
      DNZETA(9)=FOUR*KSI(IP)
      
      DNKSI(10)=ZERO
      DNETA(10)=FOUR*ZETA(IP)
      DNZETA(10)=FOUR*ETA(IP)       
C 
C     LOCAL DIFFERENTIATION OF SHAPE FUNCTIONS (DNNL/DKSI)
C
      DNNLKSI(1)=-ONE
      DNNLETA(1)=-ONE
      DNNLZETA(1)=-ONE

      DNNLKSI(2)=ONE
      DNNLETA(2)=ZERO
      DNNLZETA(2)=ZERO
      
      DNNLKSI(3)=ZERO
      DNNLETA(3)=ONE
      DNNLZETA(3)=ZERO
      
      DNNLKSI(4)=ZERO
      DNNLETA(4)=ZERO
      DNNLZETA(4)=ONE  
C 
C     COMPONENTS OF THE TRANSFORMATION MATRIX IN THE ORIGINAL CONFIGURATION (J0)
C 
C     INITIALIZE J0
C
      DO N1=1,3
      DO N2=1,3
      J0(N1,N2)=ZERO
      END DO
      END DO     
C      
      DO I=1,10
      J0(1,1)=J0(1,1)+DNKSI(I)*X0(I)
      J0(1,2)=J0(1,2)+DNKSI(I)*Y0(I)
      J0(1,3)=J0(1,3)+DNKSI(I)*Z0(I)
      J0(2,1)=J0(2,1)+DNETA(I)*X0(I)
      J0(2,2)=J0(2,2)+DNETA(I)*Y0(I)
      J0(2,3)=J0(2,3)+DNETA(I)*Z0(I)
      J0(3,1)=J0(3,1)+DNZETA(I)*X0(I)
      J0(3,2)=J0(3,2)+DNZETA(I)*Y0(I)
      J0(3,3)=J0(3,3)+DNZETA(I)*Z0(I)
      END DO          
C 
C     COMPONENTS OF THE TRANSFORMATION MATRIX IN THE MIDDLE OF THE CURRENT CONFIGURATION (JJ)
C 
C     INITIALIZE JJ
C
      DO N1=1,3
      DO N2=1,3
      JJ(N1,N2)=ZERO
      END DO
      END DO
C
      DO I=1,10
      JJ(1,1)=JJ(1,1)+DNKSI(I)*X(I)
      JJ(1,2)=JJ(1,2)+DNKSI(I)*Y(I)
      JJ(1,3)=JJ(1,3)+DNKSI(I)*Z(I)
      JJ(2,1)=JJ(2,1)+DNETA(I)*X(I)
      JJ(2,2)=JJ(2,2)+DNETA(I)*Y(I)
      JJ(2,3)=JJ(2,3)+DNETA(I)*Z(I)
      JJ(3,1)=JJ(3,1)+DNZETA(I)*X(I)
      JJ(3,2)=JJ(3,2)+DNZETA(I)*Y(I)
      JJ(3,3)=JJ(3,3)+DNZETA(I)*Z(I)
      END DO
C 
C     COMPONENTS OF THE TRANSFORMATION MATRIX IN THE END OF CURRENT CONFIGURATION (J2)
C 
C     INITIALIZE J2
C
      DO N1=1,3
      DO N2=1,3
      J2(N1,N2)=ZERO
      END DO
      END DO     
C      
      DO I=1,10
      J2(1,1)=J2(1,1)+DNKSI(I)*X2(I)
      J2(1,2)=J2(1,2)+DNKSI(I)*Y2(I)
      J2(1,3)=J2(1,3)+DNKSI(I)*Z2(I)
      J2(2,1)=J2(2,1)+DNETA(I)*X2(I)
      J2(2,2)=J2(2,2)+DNETA(I)*Y2(I)
      J2(2,3)=J2(2,3)+DNETA(I)*Z2(I)
      J2(3,1)=J2(3,1)+DNZETA(I)*X2(I)
      J2(3,2)=J2(3,2)+DNZETA(I)*Y2(I)
      J2(3,3)=J2(3,3)+DNZETA(I)*Z2(I)
      END DO        
C 
C     COMPONENTS OF THE TRANSFORMATION MATRIX FOR THE NONLOCAL VARIABLE 
C     IN THE MIDDLE OF THE CURRENT CONFIGURATION (JJNL)
C 
      DO N1=1,3
      DO N2=1,3
      JJNL(N1,N2)=ZERO
      END DO
      END DO
C
      JJNL(1,1)=-X(1)+X(2)
      JJNL(1,2)=-Y(1)+Y(2)
      JJNL(1,3)=-Z(1)+Z(2)
      JJNL(2,1)=-X(1)+X(3)
      JJNL(2,2)=-Y(1)+Y(3)
      JJNL(2,3)=-Z(1)+Z(3)
      JJNL(3,1)=-X(1)+X(4)
      JJNL(3,2)=-Y(1)+Y(4)
      JJNL(3,3)=-Z(1)+Z(4)
C 
C     COMPONENTS OF THE TRANSFORMATION MATRIX FOR THE NONLOCAL VARIABLE 
C     IN THE END OF THE CURRENT CONFIGURATION (J2NL)
C 
      DO N1=1,3
      DO N2=1,3
      J2NL(N1,N2)=ZERO
      END DO
      END DO
C
      J2NL(1,1)=-X2(1)+X2(2)
      J2NL(1,2)=-Y2(1)+Y2(2)
      J2NL(1,3)=-Z2(1)+Z2(2)
      J2NL(2,1)=-X2(1)+X2(3)
      J2NL(2,2)=-Y2(1)+Y2(3)
      J2NL(2,3)=-Z2(1)+Z2(3)
      J2NL(3,1)=-X2(1)+X2(4)
      J2NL(3,2)=-Y2(1)+Y2(4)
      J2NL(3,3)=-Z2(1)+Z2(4)  
C
C     INVERSE OF THE TRANSFORMATION MATRIX IN THE ORIGINAL CONFIGURATION (J0INV)
C
      CALL MIGS(J0,3,J0INV)           
C
C     INVERSE OF THE TRANSFORMATION MATRIX IN THE MIDDLE OF THE CURRENT CONFIGURATION (JINV)
C
      JINV = ZERO
      CALL MIGS(JJ,3,JINV)
C
C     INVERSE OF THE TRANSFORMATION MATRIX IN THE END OF THE CURRENT CONFIGURATION (J2INV)
C
      J2INV = ZERO
      CALL MIGS(J2,3,J2INV)      
C
C     INVERSE OF THE TRANSFORMATION MATRIX FOR THE NONLOCAL VARIABLE 
C     IN THE MIDDLE OF THE CURRENT CONFIGURATION (JNLINV)
C
      JNLINV = ZERO
      CALL MIGS(JJNL,3,JNLINV)
C
C     INVERSE OF THE TRANSFORMATION MATRIX FOR THE NONLOCAL VARIABLE 
C     IN THE END OF THE CURRENT CONFIGURATION (J2NLINV)
C
      J2NLINV = ZERO
      CALL MIGS(J2NL,3,J2NLINV)   
C
C     DETERMINANT OF THE TRANSFORMATION MATRIX IN THE BEGINNING OF THE CURRENT CONFIGURATION (DETJ0)
C      
      CALL KDET(J0,DETJ0)         
C
C     DETERMINANT OF THE TRANSFORMATION MATRIX IN THE MIDDLE OF THE CURRENT CONFIGURATION (DETJ)
C
      CALL KDET(JJ,DETJ)
C
C     DETERMINANT OF THE TRANSFORMATION MATRIX IN THE END OF THE CURRENT CONFIGURATION (DETJ2)
C
      CALL KDET(J2,DETJ2)      
C
C     DETERMINANT OF THE TRANSFORMATION MATRIX FOR THE NONLOCAL VARIABLE 
C     IN THE MIDDLE OF THE CURRENT CONFIGURATION (DETJNL)
C      
      CALL KDET(JJNL,DETJNL)
C
C     DETERMINANT OF THE TRANSFORMATION MATRIX FOR THE NONLOCAL VARIABLE 
C     IN THE END OF THE CURRENT CONFIGURATION (DETJ2NL)
C      
      CALL KDET(J2NL,DETJ2NL)      
C
C     ORIGINAL VOLUME DIVIDED BY CURRENT VOLUME OF ELEMENT
C      
      RELVOL = DETJ0/DETJ2
C
C     NONLOCAL SCALE LENGTH
C
      BVTV = PROPS(6)*RELVOL
      IF (BVTV .GT. 1.0D0) THEN
      BVTV = 1.0D0
      END IF
      XL = 0.0D0      
C      XL = 0.25D0*0.294D0*PROPS(6)**(-0.57D0)
C
C     GLOBAL DIFFERENTIATION OF SHAPE FUNCTIONS W.R.T THE MIDDLE OF THE CURRENT CONFIGURATION (DN/DX)
C    
      DO I=1,10
      DNX(I)=JINV(1,1)*DNKSI(I)+JINV(1,2)*DNETA(I)+JINV(1,3)*DNZETA(I)
      DNY(I)=JINV(2,1)*DNKSI(I)+JINV(2,2)*DNETA(I)+JINV(2,3)*DNZETA(I)
      DNZ(I)=JINV(3,1)*DNKSI(I)+JINV(3,2)*DNETA(I)+JINV(3,3)*DNZETA(I)
      END DO
C
C     GLOBAL DIFFERENTIATION OF SHAPE FUNCTIONS W.R.T THE END OF THE CURRENT CONFIGURATION (DN/DX2)
C    
      DO I=1,10
      DNX2(I)=J2INV(1,1)*DNKSI(I)+J2INV(1,2)*DNETA(I)+J2INV(1,3)*
     +        DNZETA(I)
      DNY2(I)=J2INV(2,1)*DNKSI(I)+J2INV(2,2)*DNETA(I)+J2INV(2,3)*
     +        DNZETA(I)
      DNZ2(I)=J2INV(3,1)*DNKSI(I)+J2INV(3,2)*DNETA(I)+J2INV(3,3)*
     +        DNZETA(I)
      END DO 
C 
C     GLOBAL DIFFERENTIATION OF SHAPE FUNCTIONS W.R.T THE ORIGINAL CONFIGURATION (DN/DX0)
C
C
      DO I=1,10
      DNX0(I)=J0INV(1,1)*DNKSI(I)+J0INV(1,2)*DNETA(I)+
     + J0INV(1,3)*DNZETA(I)
      DNY0(I)=J0INV(2,1)*DNKSI(I)+J0INV(2,2)*DNETA(I)+
     + J0INV(2,3)*DNZETA(I)
      DNZ0(I)=J0INV(3,1)*DNKSI(I)+J0INV(3,2)*DNETA(I)+
     + J0INV(3,3)*DNZETA(I)
      END DO           
C 
C     GLOBAL DIFFERENTIATION OF SHAPE FUNCTIONS W.R.T THE MIDDLE OF THE CURRENT CONFIGURATION 
C     FOR THE NONLOCAL VARIABLE (DNNL/DX)
C
      DNNLX = ZERO
      DNNLY = ZERO
      DNNLZ = ZERO
      DO I=1,4
      DNNLX(I)=JNLINV(1,1)*DNNLKSI(I)+JNLINV(1,2)*DNNLETA(I)+
     + JNLINV(1,3)*DNNLZETA(I)
      DNNLY(I)=JNLINV(2,1)*DNNLKSI(I)+JNLINV(2,2)*DNNLETA(I)+
     + JNLINV(2,3)*DNNLZETA(I)
      DNNLZ(I)=JNLINV(3,1)*DNNLKSI(I)+JNLINV(3,2)*DNNLETA(I)+
     + JNLINV(3,3)*DNNLZETA(I)
      END DO
C 
C     GLOBAL DIFFERENTIATION OF SHAPE FUNCTIONS W.R.T THE END OF THE CURRENT CONFIGURATION 
C     FOR THE NONLOCAL VARIABLE (DNNL/DX2)
C
      DNNLX2 = ZERO
      DNNLY2 = ZERO
      DNNLZ2 = ZERO
      DO I=1,4
      DNNLX2(I)=J2NLINV(1,1)*DNNLKSI(I)+J2NLINV(1,2)*DNNLETA(I)+
     + J2NLINV(1,3)*DNNLZETA(I)
      DNNLY2(I)=J2NLINV(2,1)*DNNLKSI(I)+J2NLINV(2,2)*DNNLETA(I)+
     + J2NLINV(2,3)*DNNLZETA(I)
      DNNLZ2(I)=J2NLINV(3,1)*DNNLKSI(I)+J2NLINV(3,2)*DNNLETA(I)+
     + J2NLINV(3,3)*DNNLZETA(I)
      END DO      
C
C     B MATRIX FOR STRAIN INCREMENT W.R.T THE MIDDLE OF THE CURRENT INCREMENT (B)
C
      DO I=1,10
      
      B(1,(I*3)-2)=DNX(I)
      B(1,(I*3)-1)=ZERO
      B(1,I*3)=ZERO
      
      B(2,(I*3)-2)=ZERO
      B(2,(I*3)-1)=DNY(I)
      B(2,I*3)=ZERO
      
      B(3,(I*3)-2)=ZERO
      B(3,(I*3)-1)=ZERO
      B(3,I*3)=DNZ(I)
      
      B(4,(I*3)-2)=DNY(I)
      B(4,(I*3)-1)=DNX(I)
      B(4,I*3)=ZERO
      
      B(5,(I*3)-2)=DNZ(I)
      B(5,(I*3)-1)=ZERO
      B(5,I*3)=DNX(I)
      
      B(6,(I*3)-2)=ZERO
      B(6,(I*3)-1)=DNZ(I) 
      B(6,I*3)=DNY(I)
      
      END DO
C
C     B MATRIX FOR STRAIN INCREMENT W.R.T THE END OF THE CURRENT INCREMENT (BC)
C
      DO I=1,10
      
      BC(1,(I*3)-2)=DNX2(I)
      BC(1,(I*3)-1)=ZERO
      BC(1,I*3)=ZERO
      
      BC(2,(I*3)-2)=ZERO
      BC(2,(I*3)-1)=DNY2(I)
      BC(2,I*3)=ZERO
      
      BC(3,(I*3)-2)=ZERO
      BC(3,(I*3)-1)=ZERO
      BC(3,I*3)=DNZ2(I)
      
      BC(4,(I*3)-2)=DNY2(I)
      BC(4,(I*3)-1)=DNX2(I)
      BC(4,I*3)=ZERO
      
      BC(5,(I*3)-2)=DNZ2(I)
      BC(5,(I*3)-1)=ZERO
      BC(5,I*3)=DNX2(I)
      
      BC(6,(I*3)-2)=ZERO
      BC(6,(I*3)-1)=DNZ2(I) 
      BC(6,I*3)=DNY2(I)
      END DO
C
C     B MATRIX FOR GEOMETRIC STIFFNESS MATRIX W.R.T THE END OF THE CURRENT INCREMENT (BC2)
C
      DO I=1,10
      BC1(1,3*I-2)=DNX2(I)
      
      BC1(2,3*I-2)=DNY2(I)
      
      BC1(3,3*I-2)=DNZ2(I)
      
      BC1(4,3*I-1)=DNX2(I)
      
      BC1(5,3*I-1)=DNY2(I)
      
      BC1(6,3*I-1)=DNZ2(I) 
      
      BC1(7,3*I)=DNX2(I)
      
      BC1(8,3*I)=DNY2(I)
      
      BC1(9,3*I)=DNZ2(I)        
      END DO  
      
      BC1T=TRANSPOSE(BC1)
      
      DO I=1,10
      BC2(1,3*I-2)=DNX2(I)
      
      BC2(2,3*I-2)=HALF*DNY2(I)
      BC2(2,3*I-1)=HALF*DNX2(I)
      
      BC2(3,3*I-2)=HALF*DNZ2(I)
      BC2(3,3*I)=HALF*DNX2(I)
      
      BC2(4,3*I-2)=HALF*DNY2(I)
      BC2(4,3*I-1)=HALF*DNX2(I)
      
      BC2(5,3*I-1)=DNY2(I)
      
      BC2(6,3*I-1)=HALF*DNZ2(I) 
      BC2(6,3*I)=HALF*DNY2(I) 
      
      BC2(7,3*I-2)=HALF*DNZ2(I)
      BC2(7,3*I)=HALF*DNX2(I)
      
      BC2(8,3*I-1)=HALF*DNZ2(I)
      BC2(8,3*I)=HALF*DNY2(I)   
      
      BC2(9,3*I)=DNZ2(I)        
      END DO  
C
      BC2T=TRANSPOSE(BC2)
C      
C     BETA MATRIX FOR GEOMETRIC STIFFNESS MATRIX W.R.T THE MIDDLE OF THE CURRENT INCREMENT (BETA)
C      
      DO J=1,10
         BETA(1,J)=DNX(J) 
         BETA(2,J)=DNY(J) 
         BETA(3,J)=DNZ(J)         
      END DO
C
C     B MATRIX FOR NONLOCAL KAPPA W.R.T THE MIDDLE OF THE CURRENT INCREMENT (BNL)
C      
      DO I=1,4
      BNL(1,I)=DNNLX(I)
      BNL(2,I)=DNNLY(I)
      BNL(3,I)=DNNLZ(I)
      END DO
C
C     B MATRIX FOR NONLOCAL KAPPA W.R.T THE END OF THE CURRENT INCREMENT (BNLC)
C      
      DO I=1,4
      BNLC(1,I)=DNNLX2(I)
      BNLC(2,I)=DNNLY2(I)
      BNLC(3,I)=DNNLZ2(I)
      END DO      
C
      BNLT = TRANSPOSE(BNLC)     
C      CALL KMATTRANS2(BNL,BNLT,3,4)
C
C     B MATRIX FOR SPIN (BS)
C
      DO I=1,10
      
      BS(1,(I*3)-2)=ZERO
      BS(1,(I*3)-1)=ZERO
      BS(1,I*3)=ZERO
      
      BS(2,(I*3)-2)=DNY(I)
      BS(2,(I*3)-1)=-DNX(I)
      BS(2,I*3)=ZERO
      
      BS(3,(I*3)-2)=DNZ(I)
      BS(3,(I*3)-1)=ZERO
      BS(3,I*3)=-DNX(I)
      
      BS(4,(I*3)-2)=-DNY(I)
      BS(4,(I*3)-1)=DNX(I)
      BS(4,I*3)=ZERO
      
      BS(5,(I*3)-2)=ZERO
      BS(5,(I*3)-1)=ZERO
      BS(5,I*3)=ZERO
      
      BS(6,(I*3)-2)=ZERO
      BS(6,(I*3)-1)=DNZ(I)
      BS(6,I*3)=-DNY(I)
      
      BS(7,(I*3)-2)=-DNZ(I)
      BS(7,(I*3)-1)=ZERO
      BS(7,I*3)=DNX(I)
      
      BS(8,(I*3)-2)=ZERO
      BS(8,(I*3)-1)=-DNZ(I)
      BS(8,I*3)=DNY(I)
      
      BS(9,(I*3)-2)=ZERO
      BS(9,(I*3)-1)=ZERO
      BS(9,I*3)=ZERO
      
      END DO    
C
C     TRANSPOSE OF THE B MATRIX W.R.T THE END OF THE CURRENT CONFIGURATION (BT)
C
      BT = TRANSPOSE(BC)
C      CALL KMATTRANS2(B,BT,6,30) 
C
C     CALCULATE INCREMENTAL SPIN TENSOR (DSPIN)
C
C     INCREMENTAL SPIN TENSOR IS CALCULATED AS CENTRAL 
C     DIFFERENCE INTEGRATION OF THE RATE OF SPIN, WHICH
C     IS THE ASYMMETRIC PART OF GRADIENT OF INCREMENTS
C     OF DISPLACEMENT VECTOR W.R.T THE CURRENT CONFIGURATION
C
      DO I1=1,9
      DSPINV(I1)=ZERO
      END DO
C
      DO I1=1,9
      DO I2=1,30
      DSPINV(I1)=DSPINV(I1)+BS(I1,I2)*DUV(I2)
      END DO
      END DO
C
      DSPIN(1,1)=HALF*DSPINV(1)
      DSPIN(1,2)=HALF*DSPINV(2)
      DSPIN(1,3)=HALF*DSPINV(3)
      DSPIN(2,1)=HALF*DSPINV(4)
      DSPIN(2,2)=HALF*DSPINV(5)
      DSPIN(2,3)=HALF*DSPINV(6)
      DSPIN(3,1)=HALF*DSPINV(7)
      DSPIN(3,2)=HALF*DSPINV(8)
      DSPIN(3,3)=HALF*DSPINV(9)
C
C     CALCULATE INCREMENTAL ROTATION TENSOR (DROT)
C
      DSPINHL = HALF*DSPIN
      IDSPINHL = ID + DSPINHL
      NIDSPINHL = ID-DSPINHL
      

C      CALL KSCALMAT(HALF,DSPIN,DSPINHL,3,3)
C      CALL KSUM(ID,DSPINHL,IDSPINHL,3,3)
C      CALL KSUB(ID,DSPINHL,NIDSPINHL,3,3)
      CALL MIGS(NIDSPINHL,3,NIDSPINHLINV)
      DROT=MATMUL(NIDSPINHLINV,IDSPINHL)
C      CALL KMATTRANS2(DROT,DROTT,3,3)
C
C     CALCULATE THE INCREMENTAL STRAIN TENSOR IN THE GLOBAL 
C     COORDINATE (DSTRANGC) AND IN THE LOCAL COORDINATE (DSTRAN)
C
C     INCREMENTAL STRAIN TENSOR IS CALCULATED AS CENTRAL 
C     DIFFERENCE INTEGRATION OF THE RATE OF DEFORMATION,
C     WHICH IS THE SYMMETRIC PART OF GRADIENT OF INCREMENTS
C     OF DISPLACEMENT VECTOR W.R.T THE CURRENT CONFIGURATION
C
      DSTRANGC=ZERO
      DSTRAN=ZERO
      STRAN=ZERO
C
C      CALL KMATMULTIP(B,DUV,DSTRANGC,6,30,1)
      DSTRANGC=MATMUL(B,DUV)
C
      NSTATSTRAIN=NSTATINT*(IP-1)+1+NSTATV
C
C     STORING THE STRAIN TENSOR AT THE BEGINNING OF THE CURRENT
C     INCREMENT
C
      DO I=1,6
      STRAN(I)=SVARS(NSTATSTRAIN-1+I)
      ENDDO 
C
C     STORING THE AXES OF THE LOCAL COORDINATE SYSTEM AT THE
C     BEGINNING OF THE CURRENT INCREMENT
C
      NSTATORIENT = NSTATSTRAIN + 6
C
      IF(KSTEP .EQ. 1 .AND. KINC .EQ. 1) THEN
      SVARS(NSTATORIENT)   = AA0(1)
      SVARS(NSTATORIENT+1) = AA0(2)
      SVARS(NSTATORIENT+2) = AA0(3)
      SVARS(NSTATORIENT+3) = BB0(1)
      SVARS(NSTATORIENT+4) = BB0(2)
      SVARS(NSTATORIENT+5) = BB0(3)
      SVARS(NSTATORIENT+6) = CC0(1)
      SVARS(NSTATORIENT+7) = CC0(2)
      SVARS(NSTATORIENT+8) = CC0(3)
      END IF   
C      
      AA(1) = SVARS(NSTATORIENT) 
      AA(2) = SVARS(NSTATORIENT+1)
      AA(3) = SVARS(NSTATORIENT+2)
      BB(1) = SVARS(NSTATORIENT+3)
      BB(2) = SVARS(NSTATORIENT+4)
      BB(3) = SVARS(NSTATORIENT+5)
      CC(1) = SVARS(NSTATORIENT+6)
      CC(2) = SVARS(NSTATORIENT+7)
      CC(3) = SVARS(NSTATORIENT+8)
C
C     ORIENTATION MATRIX AT THE BEGINNING OF THE CURRENT INCREMENT
C
      XAO(1,1) = AA(1)
      XAO(1,2) = AA(2)
      XAO(1,3) = AA(3)
      XAO(2,1) = BB(1)
      XAO(2,2) = BB(2)
      XAO(2,3) = BB(3)
      XAO(3,1) = CC(1)
      XAO(3,2) = CC(2)
      XAO(3,3) = CC(3)
      
C      CALL KDET(XAO,DETXAO)
C      PRINT*, 'DETXAO = ', DETXAO
C
C     TRANSPOSE OF THE ORIENTATION MATRIX AT THE BEGINNING OF THE CURRENT INCREMENT
C
      XBO(1,1) = AA(1)
      XBO(1,2) = BB(1)
      XBO(1,3) = CC(1)
      XBO(2,1) = AA(2)
      XBO(2,2) = BB(2)
      XBO(2,3) = CC(2)
      XBO(3,1) = AA(3)
      XBO(3,2) = BB(3)
      XBO(3,3) = CC(3) 
C      CALL KDET(XBO,DETXBO)
C      PRINT*, 'DETXBO = ', DETXBO
C
C     ROTATING THE AXES OF THE LOCAL COORDINATE SYSTEM
C      
      AA1=MATMUL(DROT,AA)
      BB1=MATMUL(DROT,BB)
      CC1=MATMUL(DROT,CC) 
C
C     ORIENTATION MATRIX AT THE END OF THE CURRENT INCREMENT
C      
      XA(1,1) = AA1(1)
      XA(1,2) = AA1(2)
      XA(1,3) = AA1(3)
      XA(2,1) = BB1(1)
      XA(2,2) = BB1(2)
      XA(2,3) = BB1(3)
      XA(3,1) = CC1(1)
      XA(3,2) = CC1(2)
      XA(3,3) = CC1(3) 
C
C     TRANSPOSE OF THE ORIENTATION MATRIX AT THE END OF THE CURRENT INCREMENT
C
      XB(1,1) = AA1(1)
      XB(1,2) = BB1(1)
      XB(1,3) = CC1(1)
      XB(2,1) = AA1(2)
      XB(2,2) = BB1(2)
      XB(2,3) = CC1(2)
      XB(3,1) = AA1(3)
      XB(3,2) = BB1(3)
      XB(3,3) = CC1(3) 
C
C     ROTATING THE INCREMENTAL STRAIN TENSOR FROM 
C     ELEMENT BASIS INTO MATERIAL BASIS
C 
      CALL KROT1(DSTRANGC,XA,DSTRAN)
C
C     CALCULATE THE DEFORMATION GRADIENT TENSORS IN THE GLOBAL 
C     COORDINATE FOR THE BEGINNING OF THE CURRENT INCREMENT (DFGRD0)  
C     AND THE END OF THE CURRENT INCEREMENT (DFGRD1)  
C
      DFGRD0=ZERO
      DFGRD1=ZERO
C
      DO I=1,10
      DFGRD0(1,1)=DNX0(I)*X1(I)+DFGRD0(1,1)
      DFGRD0(1,2)=DNY0(I)*X1(I)+DFGRD0(1,2)
      DFGRD0(1,3)=DNZ0(I)*X1(I)+DFGRD0(1,3)
      DFGRD0(2,1)=DNX0(I)*Y1(I)+DFGRD0(2,1)
      DFGRD0(2,2)=DNY0(I)*Y1(I)+DFGRD0(2,2)
      DFGRD0(2,3)=DNZ0(I)*Y1(I)+DFGRD0(2,3)
      DFGRD0(3,1)=DNX0(I)*Z1(I)+DFGRD0(3,1)
      DFGRD0(3,2)=DNY0(I)*Z1(I)+DFGRD0(3,2)
      DFGRD0(3,3)=DNZ0(I)*Z1(I)+DFGRD0(3,3)
      END DO
C
      DO I=1,10
      DFGRD1(1,1)=DNX0(I)*X2(I)+DFGRD1(1,1)
      DFGRD1(1,2)=DNY0(I)*X2(I)+DFGRD1(1,2)
      DFGRD1(1,3)=DNZ0(I)*X2(I)+DFGRD1(1,3)
      DFGRD1(2,1)=DNX0(I)*Y2(I)+DFGRD1(2,1)
      DFGRD1(2,2)=DNY0(I)*Y2(I)+DFGRD1(2,2)
      DFGRD1(2,3)=DNZ0(I)*Y2(I)+DFGRD1(2,3)
      DFGRD1(3,1)=DNX0(I)*Z2(I)+DFGRD1(3,1)
      DFGRD1(3,2)=DNY0(I)*Z2(I)+DFGRD1(3,2)
      DFGRD1(3,3)=DNZ0(I)*Z2(I)+DFGRD1(3,3)
      END DO    
C
      NSTATSTRESS=NSTATINT*(IP-1)+1
C
      DO I=1,NSTATV
      STATEV(I)=SVARS(NSTATSTRESS-1+I)
      ENDDO
C
      DO I=1,6
      STRESS(I)=STATEV(I)
      STRESSOLD(I)=STATEV(I)
      ENDDO
C
      DROT2 = DROT
      DROT = ID      
C
C     CALL CONSTITUTIVE ROUTINE UMAT
C
      CALL UMAT(STRESS,STATEV,DDSDDE,STRAN,DSTRAN,TIME,
     1          DTIME,PREDEF,PROPS,NPROPS,COORDS,PNEWDT,DFGRD0,
     2          DFGRD1,KSTEP,KINC,DROT,NDI,NSHR,NTENS,IP,JELEM,
     3          KAPPABAR,DKDE,DDDK,SSEFF,KAPPA1,KHAT1,NSTATV) 
C
C     ROTATING THE UPDATED STRESS TENSOR FROM THE MATERIAL BASIS
C     INTO THE ELEMENT BASIS
C
      CALL KROT2(STRESS,XB,STRESSR)
      STRESS = STRESSR
C
C     ROTATING THE UPDATED MATERIAL STIFFNESOR TENSOR FROM THE
C     MATERIAL BASIS INTO THE ELEMENT BASIS
C     
      CALL KROT3(DDSDDE,XB,DDSDDER) 
C
      DDSDDE = DDSDDER  
C
C     INITIALIZING DKDE AND SSEFF, AFTER UPDATING IN UMAT
C
C
C     ROTATING THE EFFECTIVE STRESS AND THE DERIVATIVE OF KAPPA
C     W.R.T THE STRAIN TENSOR FROM THE MATERIAL BASIS INTO THE 
C     ELEMENT BASIS
C
      CALL KROT2(DKDE,XB,DKDER)
      DKDE = DKDER      
C
      CALL KROT2(SSEFF,XB,SSEFFR)
      SSEFF = SSEFFR 
C
      DO I=1,3
      DKDE1(1,I)=DKDE(I)
      SSEFF1(I,1)=SSEFF(I)
      ENDDO
C
      DO I=4,6
      DKDE1(1,I)=DKDE(I)/DSQRT(2.D0)
      SSEFF1(I,1)=SSEFF(I)/DSQRT(2.D0)
      ENDDO      
C
      DO I=1,6
      STRAN(I)=STRAN(I)+DSTRAN(I)
      ENDDO
C
C     STORING THE UPDATED MATERIAL STATE VARIABLES (UPDATED IN UMAT)
C
      DO I=1,NSTATV
      SVARS(NSTATSTRESS-1+I)=STATEV(I)
      ENDDO
C
C     STORING THE UPDATED STRAIN TENSOR
C
      DO I=1,6
      SVARS(NSTATSTRAIN-1+I)=STRAN(I)
      ENDDO
C
C     STORING THE UPDATED LOCAL AXES
C
      SVARS(NSTATORIENT)   = AA1(1)
      SVARS(NSTATORIENT+1) = AA1(2)
      SVARS(NSTATORIENT+2) = AA1(3)
      SVARS(NSTATORIENT+3) = BB1(1)
      SVARS(NSTATORIENT+4) = BB1(2)
      SVARS(NSTATORIENT+5) = BB1(3)
      SVARS(NSTATORIENT+6) = CC1(1)
      SVARS(NSTATORIENT+7) = CC1(2)
      SVARS(NSTATORIENT+8) = CC1(3)     
C
C     ASSEMBLE ELEMENT STIFFNESS MATRIX (AMATRX) AND RIGHT-HAND-SIDE VECTOR (RHS)
C
C     RHS CONTAINS CONTRIBUTIONS OF THIS ELEMENT TO THE RIGHT-HAND-SIDE
C     VECTORS OF THE OVERAL SYSTEM OF EQUATIONS, WHICH ARE THE CONTRIBUTIONS
C     FROM THE DISTRIBUTED BODY FORCES AND THE PRESCIRBED FORCES AND/OR
C     DISPLACEMENTS ON THE BOUNDARIES OF THE STRUCTURE.
C
C     IN THE USER ELEMENT SUBROUTINE, RHS IS CALCULTED AS THE NEGATIVE OF
C     THE INTERNAL FORCES, WHICH DEPEND ON THE CURRENT STRESS STATE,
C     UPDATED IN THE USER SUBROUTINE UMAT. 
C      
C     K11M
C
      BTC=MATMUL(BT,DDSDDE)
      BTCB=MATMUL(BTC,BC)
      XK11M = DETJ2*BTCB
C
C     K11G
C
      STREXPND(1,1)=STRESSOLD(1)
      STREXPND(2,2)=STRESSOLD(2)
      STREXPND(3,3)=STRESSOLD(3)
      STREXPND(1,2)=STRESSOLD(4) 
      STREXPND(2,1)=STRESSOLD(4)   
      STREXPND(1,3)=STRESSOLD(5)  
      STREXPND(3,1)=STRESSOLD(5)
      STREXPND(2,3)=STRESSOLD(6)
      STREXPND(3,2)=STRESSOLD(6)
C      
      DO I=1,3
         DO J=1,3
            STREXPND(I+3,J+3)=STREXPND(I,J)
            STREXPND(I+6,J+6)=STREXPND(I,J)
         END DO
      END DO  
      
C      IF (KINC .EQ. 50 .AND. IP .EQ. 4) THEN
C      PRINT*, 'STRESS=',STRESS
C      PRINT*,''
C      DO I=1,9
C      DO J=1,9
C      PRINT *, 'STREXPND(',I,',',J,')=',STREXPND(I,J)
C      END DO
C      END DO
C      END IF      
C     
      BCTSTR1=MATMUL(BC1T,STREXPND)
      XK11G1=MATMUL(BCTSTR1,BC1)
      XK11G1=DETJ2*XK11G1
C      
      BCTSTR2=MATMUL(BC2T,STREXPND)
      XK11G2=MATMUL(BCTSTR2,BC2)
      XK11G2=DETJ2*XK11G2                                                            
C
C     K11
C      
      XK11=XK11M+XK11G1-TWO*XK11G2
C      XK11=XK11M+XK11G1
C      XK11=XK11M
C
C     K12
C          
      BTSEFF=MATMUL(BT,SSEFF1)
      BTSEFN=MATMUL(BTSEFF,NNL)
      XMDKDETJ = XM*DDDK*DETJ2
      XK12 = XMDKDETJ*BTSEFN
C
C     K21
C
      NNLTDK=MATMUL(NNLT,DKDE1)
      NNLTDKB=MATMUL(NNLTDK,BC)
      XK21 = DETJ2*NNLTDKB
C
C     K22
C
      NNLTNNL=MATMUL(NNLT,NNL)
      BNLTBNL=MATMUL(BNLT,BNLC)
      XL2 = XL**TWO
      XLBNLTBNL=XL2*BNLTBNL
      NTNLBTB=NNLTNNL+XLBNLTBNL
      XK22=DETJ2*NTNLBTB         
C
C     NONLOCAL FORCE
C
      NNLTNNLDK=MATMUL(NNLTNNL,KAPPABARN)
      XLBNLTBNLDK=MATMUL(XLBNLTBNL,KAPPABARN)
      XKNNLT=KAPPA1*NNLT
      FNL1=NNLTNNLDK+XLBNLTBNLDK
      FNL=FNL1-XKNNLT
C
      DO K1=1,30
      DO K2=1,30
      AMATRX(K1,K2)=AMATRX(K1,K2)+XK11(K1,K2)*W(IP)/SIX
      END DO
      END DO
C      
      DO K1=1,30
      DO K2=1,4
      AMATRX(K1,K2+30)=AMATRX(K1,K2+30)-XK12(K1,K2)*W(IP)/SIX
      END DO
      END DO           
C
      DO K1=1,4
      DO K2=1,30
      AMATRX(K1+30,K2)=AMATRX(K1+30,K2)-XK21(K1,K2)*W(IP)/SIX
      END DO
      END DO      
C     
      DO K1=1,4
      DO K2=1,4
      AMATRX(K1+30,K2+30)=AMATRX(K1+30,K2+30)+XK22(K1,K2)*W(IP)/SIX
      END DO
      END DO    
C      
      DO K1=1,30
      DO K3=1,6
      RHS(K1,1)=RHS(K1,1)-BT(K1,K3)*STRESS(K3)*DETJ2*W(IP)/SIX
      END DO
      END DO    
C      
      DO K1=1,4
      RHS(K1+30,1)=RHS(K1+30,1)-FNL(K1,1)*DETJ2*W(IP)/SIX
      END DO      
C      
      END DO    
      
C      IF (KINC .EQ. 50) THEN
C      DO I=1,30
C      DO J=1,30
C      PRINT*, 'XK11G1(',I,',',J,')=',XK11G1(I,J)
C      END DO
C      END DO
C      END IF 
     
C
C END OF THE LOOP OVER INTEGRATION POINTS
C
C
      RETURN
      END
**
***************************************************************************
**                UTILITY SUBROUTINES NEEDED FOR UEL                     **
***************************************************************************
**
**
C
C UMAT SUBROUTINE
C
      INCLUDE 'UMAT.f'
C
***************************************************************************
**
**
*************************************************
**          DETERMINANT OF A 3X3 MATRIX         *
*************************************************
C 
*USER SUBROUTINE
      SUBROUTINE KDET(A,B)
C
      INCLUDE 'ABA_PARAM.INC'
C 
      DOUBLE PRECISION A(3,3),B
      
      B = 0.0D0
C
      B =     A(1,1)*A(2,2)*A(3,3)+
     +        A(1,2)*A(2,3)*A(3,1)+
     +        A(1,3)*A(2,1)*A(3,2)-
     +        A(1,3)*A(2,2)*A(3,1)-
     +        A(1,2)*A(2,1)*A(3,3)-
     +        A(1,1)*A(2,3)*A(3,2)
C 
      RETURN
      END
**
**
***************************************************
**       MULTIPLY MXN MATRIX WITH NXP MATRIX      *
***************************************************
      SUBROUTINE KMATMULTIP(A,B,C,M,N,P)
C      
      INCLUDE 'ABA_PARAM.INC'
C  
      INTEGER M,N,P
      DOUBLE PRECISION A(M,N),B(N,P),C(M,P)
C
      C = 0.0D0
C
      DO 10 I=1,M
      DO 20 J=1,P
      X=0.D0
      DO 30 K=1,N
      Y=A(I,K)*B(K,J)
      X=X+Y
30    CONTINUE
      C(I,J)=X
20    CONTINUE
10    CONTINUE
      RETURN
      END
**
**
********************************************
**    MULTIPLY A SCALAR TO A MXN MATRIX    *
********************************************
      SUBROUTINE KSCALMAT(A,B,C,M,N)
C      
      INCLUDE 'ABA_PARAM.INC'
C 
      INTEGER M,N
      DOUBLE PRECISION B(M,N),C(M,N)
      DOUBLE PRECISION A
C
      C = 0.0D0
C 
      DO 10 I=1,M
      DO 20 J=1,N
      C(I,J)=A*B(I,J)
   20 CONTINUE
   10 CONTINUE
      RETURN
      END
********************************************
**         SUM UP TWO MXN MATRICES         *
********************************************
      SUBROUTINE KSUM(A,B,C,M,N)
C      
      INCLUDE 'ABA_PARAM.INC'
C  
      INTEGER M,N
      DOUBLE PRECISION A(M,N),B(M,N),C(M,N)
C
      C = 0.0D0
C 
      DO I=1,M
       DO J=1,N
        C(I,J) = A(I,J)+B(I,J)
       END DO
      END DO
      RETURN
      END
**
**
********************************************
**      SUBTRACT TWO MXN MATRICES (A-B)    *
********************************************
      SUBROUTINE KSUB(A,B,C,M,N)
C      
      INCLUDE 'ABA_PARAM.INC'
C  
      INTEGER M,N
      DOUBLE PRECISION A(M,N),B(M,N),C(M,N)
C
      C = 0.0D0
C 
      DO I=1,M
       DO J=1,N
        C(I,J) = A(I,J)-B(I,J)
       END DO
      END DO
      RETURN
      END
**
**
********************************************
**       TRANSPOSE A MxN MATRIX            *
********************************************
      SUBROUTINE KMATTRANS2(A,B,M,N)
C
      INCLUDE 'ABA_PARAM.INC'
C
      INTEGER M, N
      DOUBLE PRECISION A(M,N), B(N,M)
C
      B = 0.0D0
C
      DO 20 I = 1,M
      DO 10 J = 1,N
      B(J,I) = A(I,J)
   10 CONTINUE
   20 CONTINUE
C
      RETURN
      END 
**
**
******************************************** 
**     SUBROUTINES FOR MATRIX INVERSION    *
********************************************
      SUBROUTINE MIGS(A,N,X)
C
C     Subroutine to invert matrix A(N,N) with the inverse stored
C     in X(N,N) in the output. A is stored in STOA and is resituted
C     as outpout
C 
      IMPLICIT NONE
C 
      DOUBLE PRECISION A(N,N),STOA(N,N),B(N,N),X(N,N)
      INTEGER INDX(N),N,I,J,K
C 
      DO 140 I=1,N
        DO 130 J=1,N
          STOA(I,J)=A(I,J)
          B(I,J)=0.0D0
  130   CONTINUE
  140 CONTINUE
      DO 150 I=1,N
        B(I,I)=1.0D0
  150 CONTINUE
C 
      CALL ELGS(A,N,INDX)
C 
      DO 180 I=1,N-1
        DO 170 J=I+1,N
          DO 160 K=1,N
            B(INDX(J),K)=B(INDX(J),K)
     1                    -A(INDX(J),I)*B(INDX(I),K)
  160     CONTINUE
  170   CONTINUE
  180 CONTINUE
C 
      DO 210 I=1,N
        X(N,I)=B(INDX(N),I)/A(INDX(N),N)
        DO 200 J=N-1,1,-1
          X(J,I)=B(INDX(J),I)
          DO 190 K=J+1,N
            X(J,I)=X(J,I)-A(INDX(J),K)*X(K,I)
  190     CONTINUE
          X(J,I)= X(J,I)/A(INDX(J),J)
  200   CONTINUE
  210 CONTINUE
C
C Restitution of A
C 
      DO 230 I=1,N
        DO 220 J=1,N
          A(I,J)=STOA(I,J)
  220   CONTINUE
  230 CONTINUE
C 
      RETURN
      END
********************************************
      SUBROUTINE ELGS(A,N,INDX)
C
C     Subroutine to perform the partial-pivoting Gaussian elimination.
C     A(N,N) is the original matrix in the input and transformed
C     matrix plus the pivoting element ratios below the diagonal in
C     the output.  INDX(N) records the pivoting order.
C 
      IMPLICIT NONE
C 
      DOUBLE PRECISION A(N,N),C(N)
      INTEGER N, INDX(N)
      DOUBLE PRECISION C1,PI1,PI,PJ
      INTEGER K,ITMP,I,J
C
C     Initialize the index
C 
      DO 240 I=1,N
        INDX(I)=I
  240 CONTINUE
C
C     Find the rescaling factors, one from each row
C 
        DO 260 I=1,N
          C1= 0.0
          DO 250 J=1,N
            C1=DMAX1(C1,DABS(A(I,J)))
  250     CONTINUE
          C(I)=C1
  260   CONTINUE
C
C     Search the pivoting (largest) element from each column
C 
      DO 300 J=1,N-1
        PI1=0.0
        DO 270 I=J,N
          PI=DABS(A(INDX(I),J))/C(INDX(I))
          IF (PI.GT.PI1) THEN
            PI1=PI
            K=I
          ELSE
          END IF
  270   CONTINUE
C
C     Interchange the rows via INDX(N) to record pivoting order
C 
        ITMP=INDX(J)
        INDX(J)=INDX(K)
        INDX(K)=ITMP
        DO 290 I=J+1,N
          PJ=A(INDX(I),J)/A(INDX(J),J)
C
C     Record pivoting ratios below the diagonal
C 
          A(INDX(I),J)=PJ
C
C     Modify other elements accordingly
C 
          DO 280 K=J+1,N
            A(INDX(I),K)=A(INDX(I),K)-PJ*A(INDX(J),K)
  280     CONTINUE
  290   CONTINUE
  300 CONTINUE
C 
      RETURN
      END
********************************************
**
***************************************************************************
**                UTILITY SUBROUTINES NEEDED FOR UMAT                    **
***************************************************************************
**
***************************************************
**         MULTIPLY 6X6 MATRIX WITH 6X1 VECTOR    *
***************************************************
*USER SUBROUTINE
      SUBROUTINE KMLT1(A,B,C)
C      
      INCLUDE 'ABA_PARAM.INC'
C 
      DOUBLE PRECISION A(6,6),B(6),C(6)
C
      C = 0.0D0
C 
      DO 10 I=1,6
      X=0.D0
      DO 20 K=1,6
      Y=A(I,K)*B(K)
      X=X+Y
20    CONTINUE
      C(I)=X
10    CONTINUE
      RETURN
      END
**
**
************************************************************************
**          ROTATE THE STRAIN TENSOR WRITTEN IN VOIGT NOTATION         *
**                FROM ELEMENT BASIS TO MATERIAL BASIS                 *
************************************************************************
*USER SUBROUTINE
      SUBROUTINE KROT1(A,B,C)
C      
      INCLUDE 'ABA_PARAM.INC'
C
      DOUBLE PRECISION A(6), B(3,3), C(6), AA(3,3), CC(3,3)
      INTEGER I, J, K, L
C
      C = 0.0D0
      AA = 0.0D0
      CC = 0.0D0 
C
      AA(1,1) = A(1)
      AA(2,2) = A(2)
      AA(3,3) = A(3)
      AA(1,2) = A(4)/2.0D0
      AA(1,3) = A(5)/2.0D0
      AA(2,3) = A(6)/2.0D0
      AA(2,1) = AA(1,2)
      AA(3,1) = AA(1,3)
      AA(3,2) = AA(2,3)
C
      DO I=1,3
      DO J=1,3
       CC(I,J) = 0.0D0
       DO K=1,3
       DO L=1,3
       CC(I,J)=AA(K,L)*B(I,K)*B(J,L)+CC(I,J)
       END DO
       END DO
      END DO
      END DO
C
      C(1) = CC(1,1)
      C(2) = CC(2,2)
      C(3) = CC(3,3)
      C(4) = CC(1,2)*2.0D0
      C(5) = CC(1,3)*2.0D0
      C(6) = CC(2,3)*2.0D0
C
      RETURN
      END 
**     
************************************************************************
**          ROTATE THE STRESS TENSOR WRITTEN IN VOIGT NOTATION         *
**                FROM MATERIAL BASIS TO ELEMENT BASIS                 *
************************************************************************
*USER SUBROUTINE
      SUBROUTINE KROT2(A,B,C)
C      
      INCLUDE 'ABA_PARAM.INC'
C
      DOUBLE PRECISION A(6), B(3,3), C(6), AA(3,3), CC(3,3)
      INTEGER I, J, K, L
C
      C = 0.0D0
      AA = 0.0D0
      CC = 0.0D0
C
      AA(1,1) = A(1)
      AA(2,2) = A(2)
      AA(3,3) = A(3)
      AA(1,2) = A(4)
      AA(1,3) = A(5)
      AA(2,3) = A(6)
      AA(2,1) = AA(1,2)
      AA(3,1) = AA(1,3)
      AA(3,2) = AA(2,3)
C
      DO I=1,3
      DO J=1,3
       CC(I,J) = 0.0D0
       DO K=1,3
       DO L=1,3
       CC(I,J)=AA(K,L)*B(I,K)*B(J,L)+CC(I,J)
       END DO
       END DO
      END DO
      END DO
C
      C(1) = CC(1,1)
      C(2) = CC(2,2)
      C(3) = CC(3,3)
      C(4) = CC(1,2)
      C(5) = CC(1,3)
      C(6) = CC(2,3)
C
      RETURN
      END 
**
**
************************************************************************************
**          ROTATE THE MATERIAL STIFFNESS TENSOR WRITTEN IN VOIGT NOTATION         *
**                       FROM MATERIAL BASIS INTO ELEMENT BASIS                    *
************************************************************************************
C 
*USER SUBROUTINE
      SUBROUTINE KROT3(A,B,C)
C      
      INCLUDE 'ABA_PARAM.INC'
C 
      DOUBLE PRECISION A(6,6),B(3,3),C(6,6),AA(3,3,3,3),CC(3,3,3,3)
C
      INTEGER I,J,K,L,M,N,P,Q,i2I(6),j2J(6)
C 
      DATA i2I / 1,2,3,1,1,2 /, 
     &     j2J / 1,2,3,2,3,3 /
C
      AA = 0.0D0
C      CC = 0.0D0
      C = 0.0D0             
C       
      DO I = 1, 6
      DO J = 1, 6
         AA(i2I(I),j2J(I),i2I(J),j2J(J)) = A(I,J)
         AA(i2I(I),j2J(I),j2J(J),i2I(J)) = A(I,J)         
         AA(j2J(I),i2I(I),i2I(J),j2J(J)) = A(I,J)
         AA(j2J(I),i2I(I),j2J(J),i2I(J)) = A(I,J)
      ENDDO
      ENDDO
C
      DO I=1,3
      DO J=1,3
      DO K=1,3
      DO L=1,3
C     
      CC(I,J,K,L) = 0.0D0
C
        DO M=1,3
        DO N=1,3
        DO P=1,3
        DO Q=1,3
C 
        CC(I,J,K,L)=AA(M,N,P,Q)*B(I,M)*B(J,N)*B(K,P)*B(L,Q)+
     +              CC(I,J,K,L)
C 
        ENDDO
        ENDDO
        ENDDO
        ENDDO
C 
      ENDDO
      ENDDO
      ENDDO
      ENDDO      
C
      C(1,1)=CC(1,1,1,1)
      C(1,2)=CC(1,1,2,2)
      C(1,3)=CC(1,1,3,3)
      C(1,4)=CC(1,1,1,2)
      C(1,5)=CC(1,1,1,3)
      C(1,6)=CC(1,1,2,3)
C
      C(2,1)=CC(2,2,1,1)
      C(2,2)=CC(2,2,2,2)
      C(2,3)=CC(2,2,3,3)
      C(2,4)=CC(2,2,1,2)
      C(2,5)=CC(2,2,1,3)
      C(2,6)=CC(2,2,2,3)  
C
      C(3,1)=CC(3,3,1,1)
      C(3,2)=CC(3,3,2,2)
      C(3,3)=CC(3,3,3,3)
      C(3,4)=CC(3,3,1,2)
      C(3,5)=CC(3,3,1,3)
      C(3,6)=CC(3,3,2,3)   
C
      C(4,1)=CC(1,2,1,1)
      C(4,2)=CC(1,2,2,2)
      C(4,3)=CC(1,2,3,3)
      C(4,4)=CC(1,2,1,2)
      C(4,5)=CC(1,2,1,3)
      C(4,6)=CC(1,2,2,3)     
C
      C(5,1)=CC(1,3,1,1)
      C(5,2)=CC(1,3,2,2)
      C(5,3)=CC(1,3,3,3)
      C(5,4)=CC(1,3,1,2)
      C(5,5)=CC(1,3,1,3)
      C(5,6)=CC(1,3,2,3)   
C
      C(6,1)=CC(2,3,1,1)
      C(6,2)=CC(2,3,2,2)
      C(6,3)=CC(2,3,3,3)
      C(6,4)=CC(2,3,1,2)
      C(6,5)=CC(2,3,1,3)
      C(6,6)=CC(2,3,2,3)  
C
C      DO I = 1, 6
C      DO J = 1, 6
C         C(I,J) = CC(j2J(I),i2I(I),i2I(J),j2J(J))
C      ENDDO
C      ENDDO                            
C 
      RETURN
      END
**
**
*****************************************************
**          A DYD UNDERLINE B IN 6X6 FORMAT         *
*****************************************************
C 
*USER SUBROUTINE
      SUBROUTINE KADYDUB(A,B,C)
C      
      INCLUDE 'ABA_PARAM.INC'
C 
      DOUBLE PRECISION A(3,3),B(3,3),C(6,6)
C
      C = 0.0D0
C       
      C(1,1) = A(1,1)*B(1,1)
      C(1,2) = A(1,2)*B(1,2)
      C(1,3) = A(1,3)*B(1,3)
      C(1,4) = 0.5D0*(A(1,3)*B(1,2)+A(1,2)*B(1,3))
      C(1,5) = 0.5D0*(A(1,3)*B(1,1)+A(1,1)*B(1,3))
      C(1,6) = 0.5D0*(A(1,2)*B(1,1)+A(1,1)*B(1,2))
      
      C(2,1) = A(2,1)*B(2,1)
      C(2,2) = A(2,2)*B(2,2)
      C(2,3) = A(2,3)*B(2,3)
      C(2,4) = 0.5D0*(A(2,3)*B(2,2)+A(2,2)*B(2,3))
      C(2,5) = 0.5D0*(A(2,3)*B(2,1)+A(2,1)*B(2,3))
      C(2,6) = 0.5D0*(A(2,2)*B(2,1)+A(2,1)*B(2,2))
      
      C(3,1) = A(1,3)*B(1,3)
      C(3,2) = A(2,3)*B(2,3)
      C(3,3) = A(3,3)*B(3,3)
      C(3,4) = 0.5D0*(A(3,3)*B(2,3)+A(2,3)*B(3,3))
      C(3,5) = 0.5D0*(A(3,3)*B(1,3)+A(1,3)*B(3,3))
      C(3,6) = 0.5D0*(A(2,3)*B(1,3)+A(1,3)*B(2,3))
      
      C(4,1) = 0.5D0*(A(2,1)*B(1,3)+A(1,3)*B(2,1))
      C(4,2) = 0.5D0*(A(2,3)*B(2,2)+A(2,2)*B(2,3))
      C(4,3) = 0.5D0*(A(3,3)*B(2,3)+A(2,3)*B(3,3))
      C(4,4) = 0.25D0*(A(3,3)*B(2,2)+2.0D0*A(2,3)*
     + B(2,3)+A(2,2)*B(3,3))
      C(4,5) = 0.25D0*(A(2,3)*B(1,3)+A(3,3)*B(2,1)+
     + A(1,3)*B(2,3)+A(2,1)*B(3,3))
      C(4,6) = 0.25D0*(A(2,2)*B(1,3)+A(2,3)*B(2,1)+
     + A(1,3)*B(2,2)+A(2,1)*B(2,3))
      
      C(5,1) = 0.5D0*(A(1,3)*B(1,1)+A(1,1)*B(1,3))
      C(5,2) = 0.5D0*(A(2,3)*B(1,2)+A(1,2)*B(2,3))
      C(5,3) = 0.5D0*(A(3,3)*B(1,3)+A(1,3)*B(3,3))
      C(5,4) = 0.25D0*(A(3,3)*B(1,2)+A(2,3)*B(1,3)+
     + A(1,3)*B(2,3)+A(1,2)*B(3,3))
      C(5,5) = 0.25D0*(A(3,3)*B(1,1)+2.0D0*A(1,3)*
     + B(1,3)+A(1,1)*B(3,3))
      C(5,6) = 0.25D0*(A(2,3)*B(1,1)+A(1,3)*B(1,2)+
     + A(1,2)*B(1,3)+A(1,1)*B(2,3))
      
      C(6,1) = 0.5D0*(A(2,1)*B(1,1)+A(1,1)*B(2,1))
      C(6,2) = 0.5D0*(A(2,2)*B(1,2)+A(1,2)*B(2,2))
      C(6,3) = 0.5D0*(A(2,3)*B(1,3)+A(1,3)*B(2,3))
      C(6,4) = 0.25D0*(A(2,3)*B(1,2)+A(2,2)*B(1,3)+
     + A(1,3)*B(2,2)+A(1,2)*B(2,3))
      C(6,5) = 0.25D0*(A(2,3)*B(1,1)+A(2,1)*B(1,3)+
     + A(1,3)*B(2,1)+A(1,1)*B(2,3))
      C(6,6) = 0.25D0*(A(2,2)*B(1,1)+A(2,1)*B(1,2)+
     + A(1,2)*B(2,1)+A(1,1)*B(2,2))
C 
      RETURN
      END
**
**
*****************************************************************
**        CALCULATE THE CONDITION NUMBER OF A NXN MATRIX        *
*****************************************************************
**
*USER SUBROUTINE
      SUBROUTINE KCONDNO(A,N,C)
C     
C     The condition number of a matrix measures the sensitivity of 
C     the solution of a system of linear equations to errors in the data.  
C
      INCLUDE 'ABA_PARAM.INC'
C
      DOUBLE PRECISION A(N,N), B(N,N)
      DOUBLE PRECISION C, X, Y
      INTEGER N
C 
      CALL MIGS(A,N,B)
C 
C     B IS THE INVERSE OF A
C
      X=0.D0
      Y=0.D0
C 
C     X AND Y ARE EUCLEADIAN NORMS OF A AND B RESPECTIVELY
C
      DO I=1,N
      DO J=1,N
       X=X+A(I,J)*A(I,J)
       Y=Y+B(I,J)*B(I,J)
      END DO
      END DO
C
      C=DSQRT(X)*DSQRT(Y)
C
      RETURN
      END
**
**













