CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C UMAT FOR ELASTIC VISCOPLASTIC NONLOCAL DAMAGE UEL
C
C CREATED BY JAKOB SCHWIEDRZIK - ISTB - 2012
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C INCLUDING DENSIFICATION ROUTINE
C
C CREATED BY HADI SEYED HOSSEINI - ILSB - 2011
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C       MODIFICATIONS                       
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C  * D E P V A R  
C
C    SDV 1-6: TOTAL STRESS TENSOR 
C    SDV 7: CUMULATED PLASTIC STRAIN
C    SDV 8: SCALAR DAMAGAE VARIABLE
C    SDV 9-14: PLASTIC STRAIN VECTOR
C    SDV 15-20: NOMINAL STRESS VECTOR
C    SDV 21-26: DENSIFICATION STRESS VECTOR
C    SDV 27: ORIGINAL BVTV
C    SDV 28: UPDATED BVTV 
C
C  * U S E R   M A T E R I A L    
C
C     PROPS(1) - BONE FLAG:         0 - TRABECULAR BONE
C                                   1 - CORTICAL BONE
C     PROPS(2) - BVTV
C     PROPS(3) - MM1
C     PROPS(4) - MM2
C     PROPS(5) - MM3
C     PROPS(6) - DENSIFICATOR FLAG: 0 - DENSIFICATION OFF
C                                   1 - DENSIFICATION ON
C     PROPS(7) - VISCOSITY FLAG:    0 - RATE-INDEPENDENT
C                                   1 - LINEAR VISCOSITY
C                                   2 - EXPONENTIAL VISC
C                                   3 - LOGARITHMIC VISC
C                                   4 - POLYNOMIAL VISC
C                                   5 - POWER LAW VISC 
C     PROPS(8) - POSTYIELD FLAG:    0 - PERFECT PLASTICITY
C                                   1 - LINEAR HARDENING
C                                   2 - EXPONENTIAL HARDENING
C                                   3 - QUADRATIC HARDENING
C     PROPS(9) - XM:                NONLOCAL WEIGHT
C
C  M E D T O O L  T E M P L A T E 
C     ** XXX to be replaced by user
C     ** CardName BVTV, EigVal.., replace by medtool 
C     *MATERIAL, NAME=CardName
C     *DEPVAR
C     2
C     *USER MATERIAL, CONSTANTS=5, UNSYMM
C     XXX, BVTV, EigVal3, EigVal2,  EigVal1
CC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,RPL,DDSDDT,
C     1                DRPLDE,DRPLDT,STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,
C     2                PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,NSTATV,PROPS,
C     3                NPROPS,COORDS,DROT,PNEWDT,CELENT,DFGRD0,DFGRD1,
C     4                NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
     
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,RPL,DDSDDT,
     1                DRPLDE,DRPLDT,STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,
     2                PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,NSTATV,PROPS,
     3                NPROPS,COORDS,DROT,PNEWDT,CELENT,DFGRD0,DFGRD1,
     4                NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C
      IMPLICIT NONE
C
C     INPUT/OUTPUT VARIABLES:
      INTEGER NTENS, NDI, NSHR
      INTEGER NSTATV      
      INTEGER NPROPS
C
C     INPUT/OUTPUT VARIABLES THAT HAVE TO BE DEFINED BY THE UMAT
C     IN ALL SITUATIONS:
      DOUBLE PRECISION STRESS(NTENS), STATEV(NSTATV)
      DOUBLE PRECISION DDSDDE(NTENS,NTENS)
      DOUBLE PRECISION SSE,SPD,SCD
C
C     ONLY IN FULLY COUPLED TEMPERATURE-DISPLACEMENT ANALYSIS:
      DOUBLE PRECISION RPL,DDSDDT(NTENS),DRPLDE(NTENS),DRPLDT
C
C     OUTPUT VARIABLES THAT CAN BE UPDATED WITHIN THE UMAT (TIME INC):
      DOUBLE PRECISION PNEWDT
C
C     INPUT VARIABLES: SUPPLIED BY ABAQUS:
      DOUBLE PRECISION STRAN(NTENS), DSTRAN(NTENS)
      DOUBLE PRECISION TIME(2)     , DTIME
      DOUBLE PRECISION TEMP        , DTEMP
      DOUBLE PRECISION PREDEF(1)   , DPRED(1)
      CHARACTER*8      CMNAME
      DOUBLE PRECISION PROPS(NPROPS)
      DOUBLE PRECISION COORDS(3)
      DOUBLE PRECISION DROT(3,3)
      DOUBLE PRECISION CELENT
      DOUBLE PRECISION DFGRD0(3,3) , DFGRD1(3,3)
      INTEGER          NOEL,NPT,LAYER,KSPT,KSTEP,KINC
C
C     EXTERNAL FUNCTIONS
      DOUBLE PRECISION RADK,DRADK,DAM,DDAM,VECNORM,KDET 
      DOUBLE PRECISION VISCY,VDYDK
C
C     VISCOPLASTIC DAMAGE UMAT VARIABLES
      INTEGER ITER,MAXITER,BF,K1,K2,DENSFL,VISCFL,PYFL
      DOUBLE PRECISION DETF0,MM,ETA,TOL,KONSTD,CRITD
      DOUBLE PRECISION RHO,MM1,MM2,MM3
      DOUBLE PRECISION VXM1,VYM1,VZM1,VXM2,VYM2,VZM2
      DOUBLE PRECISION E0,V0,MU0,KS,LS
      DOUBLE PRECISION SIGD0P,SIGD0N,CHID0,TAUD0,PP,QQ
      DOUBLE PRECISION E11,E22,E33,V12,V13,V23,MU12,MU13,MU23
      DOUBLE PRECISION SIGD1P,SIGD1N,SIGD2P,SIGD2N,SIGD3P,SIGD3N
      DOUBLE PRECISION TAUD12,TAUD13,TAUD23,CHID12,CHID13,CHID23
      DOUBLE PRECISION EPS0P,EPS0N,EPS0S,PSI0,S0
      DOUBLE PRECISION EXPS,KMAX,KWIDTH,RDY,RDY2,PDY,P1,P2,P3,P4
      DOUBLE PRECISION KMIN,GMIN,ND
      DOUBLE PRECISION SSSS(NTENS,NTENS),CCCC(NTENS,NTENS)
      DOUBLE PRECISION AAAA(NTENS,NTENS),AA(NTENS)
      DOUBLE PRECISION DDDD(NTENS,NTENS),DD(NTENS)
      DOUBLE PRECISION DDSY(NTENS,NTENS),DSY(NTENS)
      DOUBLE PRECISION ETOT1(NTENS),ETOT0(NTENS),SS0(NTENS)
      DOUBLE PRECISION KAPPA0,DKAPPAI,DKAPPA1,DDK1,KAPPA1
      DOUBLE PRECISION STR(NTENS),SSI(NTENS),SS1(NTENS),DSS1(NTENS)
      DOUBLE PRECISION EPLAS0(NTENS),EPLAS1(NTENS)
      DOUBLE PRECISION YSTR,YS,DYDS(NTENS),DYDK,DMG0
      DOUBLE PRECISION DMG,DDMG,RAD,DRAD,DDS(NTENS),SDDS,SRA(NTENS)
      DOUBLE PRECISION NP(NTENS),DNPDS(NTENS,NTENS),DNPDK(NTENS)
      DOUBLE PRECISION RR(NTENS),DRRDS(NTENS,NTENS),DRRDK(NTENS)
      DOUBLE PRECISION HI,DHDS(NTENS),DHDK,NORMRR,ABSY
      DOUBLE PRECISION SSSA(NTENS,NTENS),TANM(NTENS,NTENS)
C
C     PRIMAL CPP ALGORITHM AND LINE SEARCH VARIABLES
      INTEGER ITERL,FLAG
      DOUBLE PRECISION J11(6,6),J22,J12(6),J21(6)
      DOUBLE PRECISION RRR(7),RRI(7),XXI(7),XX1(7),DDD(7),JJJ(7,7)
      DOUBLE PRECISION INVJ(7,7),DDJ(7,7),AUX,DMK,UPLIM
      DOUBLE PRECISION ETAL,BETA,MKI,MK1,ALPHA1,ALPHA2,ALPHA
C
C     DENSIFICATOR ROUTINE VARIABLES
      DOUBLE PRECISION ECRIT,GAMMAL0,RL,GAMMAP0,RP,POWERDNS
      DOUBLE PRECISION TRACEEN,CRITERION,GAMMAL,GAMMAP
      DOUBLE PRECISION SDNS(6),SDNST(3,3),XIDENV(6),XIDEN(3,3)
      DOUBLE PRECISION XDENSSTIFF1,TANGDENS(6,6)
C
C     NONLOCAL PARAMETERS
      DOUBLE PRECISION XM, KAPPABAR, KHAT1
C 
C     INTERFACE FOR ARRAY VALUED EXTERNAL FUNCTION VECDYAD
      INTERFACE
      FUNCTION VECDYAD(BB,CC)
      DOUBLE PRECISION VECDYAD(6,6)
      DOUBLE PRECISION BB(6),CC(6)
      END FUNCTION VECDYAD
      END INTERFACE
C
      DOUBLE PRECISION DKDE(6),DDDK, SSEFF(6)
C
C     DOT_PRODUCT(VECTOR_A, VECTOR_B) SCALAR PRODUCT
C     MATMUL(MATRIX_A, MATRIX_B) MATRIX MULTIPLICATION
C 
C     TENSOR INITIALISATION
C 
      SSSS=0.0D0
      CCCC=0.0D0
      AAAA=0.0D0
      DDDD=0.0D0
      DDSY=0.0D0
      DNPDS=0.0D0
      DRRDS=0.0D0
      SSSA=0.0D0
      TANM=0.0D0
      TANGDENS=0.0D0
C
      XIDEN=0.0D0
C 
      DO K1=1,3
         XIDEN(K1,K1)=1.0D0
      ENDDO
C
C     VECTOR INITIALISATION
C 
      DD=0.0D0
      ETOT1=0.0D0
      ETOT0=0.0D0
      SS0=0.0D0
      STR=0.0D0
      SSI=0.0D0
      SS1=0.0D0
      DSS1=0.0D0
      EPLAS0=0.0D0
      EPLAS1=0.0D0
      DYDS=0.0D0
      DDS=0.0D0
      NP=0.0D0
      DNPDK=0.0D0
      RR=0.0D0
      DRRDK=0.0D0
      DHDS=0.0D0
      DKDE=0.0D0
      SSEFF=0.0D0
C
      XIDENV=0.0D0
C 
      DO K1=1,3
         XIDENV(K1)=1.0D0
      ENDDO  
C
C     SCALAR INITIALISATION
C 
      ITER=0
      K1=0
      K2=0
      MM=0.0D0
      ETA=0.0D0
      RDY=0.0D0
      RDY2=0.0D0
      KAPPA0=0.0D0
      DKAPPAI=0.0D0
      DKAPPA1=0.0D0
      DDK1=0.0D0
      KAPPA1=0.0D0
      KHAT1=0.0D0
      YSTR=0.0D0
      YS=0.0D0
      DYDK=0.0D0
      DMG=0.0D0
      DMG0=0.0D0
      DDMG=0.0D0
      RAD=0.0D0
      DRAD=0.0D0
      SDDS=0.0D0
      HI=0.0D0
      DHDK=0.0D0
      NORMRR=0.0D0
      ABSY=1.0D0
      EXPS=1.0D0
      KMAX=1.0D0
      KWIDTH=1.0D0
      KONSTD=0.0D0
      CRITD=0.0D0
      RHO=0.0D0
      S0=0.0D0
      XDENSSTIFF1=0.0D0
      DDDK = 0.0D0
C
C     TOLERANCE OF NUMERICAL ERROR  
C 
      TOL=1.0D-12
C
C     MAXIMUM ALLOWED ITERATIONS  
C 
      MAXITER=100
C
      BF=PROPS(1)
      DENSFL=PROPS(2)
      VISCFL=PROPS(3)
      PYFL=PROPS(4)
      XM=0.0D0
      RHO=PROPS(6)
      MM1=PROPS(7)
      MM2=PROPS(8)
      MM3=PROPS(9)
      VXM1=PROPS(10)
      VYM1=PROPS(11)
      VZM1=PROPS(12)
      VXM2=PROPS(13)
      VYM2=PROPS(14)
      VZM2=PROPS(15)
C
C     VISCOPLASTICITY PARAMETERS
C 
      MM=0.1D0
C      ETA=0.0D0
      ETA=0.01D0
C
C     ELASTICITY PARAMETERS: UMAT REPORT
C 
      E0=9995.0D0
      V0=0.2278D0
      MU0=3361.0D0
      KS=1.62D0
      LS=1.1D0
C
C     PLASTIC PARAMETERS: UMAT REPORT 
C     IN WOLFRAM-2012 YIELD PARAMETERS BASED ON 0.2% STRAIN ARE GIVEN;
C     HOWEVER, THESE VALUES ARE SCALED TO OBTAIN THE ULTIMATE  
C     STRENGTH VALUES USED IN THIS UMAT.
C     
      SIGD0P=66.01D0*1000
      SIGD0N=98.88D0*1000
      CHID0=0.2182D0
      TAUD0=41.89D0*1000
      PP=1.69D0
      QQ=1.05D0
C
C     DAMAGE PARAMETERS
C 
      KONSTD=7.0D0
      CRITD=0.75D0
C
C     HARDENING PARAMETERS
C 
      EXPS=100.0D0
      KMAX=0.02D0
C     
C     ORIGINAL CHARLEBOIS MODEL
C
      RDY=1.5D0
C
C     PEAK AT 1.0
C
      P1 = DEXP(-KONSTD*KMAX)
      P2 = DEXP(-2.0D0*KONSTD*KMAX)
      P3 = DEXP(EXPS*KMAX)
      P4 = P3/(1.0D0-DAM(KMAX,KONSTD,CRITD))
      PDY = -(CRITD*KONSTD*P1+EXPS-EXPS*CRITD+EXPS*CRITD*P1)/
     +      (EXPS*(-1.0D0+2.0D0*CRITD-2.0D0*CRITD*P1-CRITD**2.0D0 +
     +      2.0D0*CRITD**2.0D0*P1-CRITD**2.0D0*P2))
      RDY2 = P4-PDY*(P3-1.0D0)  
      
      IF (NOEL .EQ. 1 .AND. NPT .EQ. 1 .AND. KINC .EQ. 1 .AND. 
     +     KSTEP .EQ. 1) THEN
      PRINT*, 'RELATIVE YIELD = ',  RDY2
      END IF    
C
C     DENSITY-BASED DENSIFICATION PARAMETERS
C
      ECRIT = -0.3
      GAMMAL0 = 1100.0D0
      RL = 2.928D0
      GAMMAP0 = 1300.0D0
      RP = 2.77D0
      POWERDNS = 6.0D0
C
C     FABRIC-BASED ORTHOTROPIC STIFFNESS TENSOR SSSS (RINCON&ZYSSET, 2008)
C 
      SSSS(1,1)=E0*(1.0D0-V0)/(1.0D0+V0)/(1.0D0-2.0D0*V0)*MM1
     1   **(2.0D0*LS)*RHO**KS
      SSSS(2,2)=E0*(1.0D0-V0)/(1.0D0+V0)/(1.0D0-2.0D0*V0)*MM2
     1   **(2.0D0*LS)*RHO**KS
      SSSS(3,3)=E0*(1.0D0-V0)/(1.0D0+V0)/(1.0D0-2.0D0*V0)*MM3
     1   **(2.0D0*LS)*RHO**KS
      SSSS(4,4)=2.0D0*MU0*(MM1**LS)*(MM2**LS)*RHO**KS
      SSSS(5,5)=2.0D0*MU0*(MM3**LS)*(MM1**LS)*RHO**KS
      SSSS(6,6)=2.0D0*MU0*(MM2**LS)*(MM3**LS)*RHO**KS
      SSSS(2,1)=E0*V0/(1.0D0+V0)/(1.0D0-2.0D0*V0)*(MM1**LS)*(MM2**LS)
     1   *RHO**KS
      SSSS(3,1)=E0*V0/(1.0D0+V0)/(1.0D0-2.0D0*V0)*(MM3**LS)*(MM1**LS)
     1   *RHO**KS
      SSSS(3,2)=E0*V0/(1.0D0+V0)/(1.0D0-2.0D0*V0)*(MM2**LS)*(MM3**LS)
     1   *RHO**KS
      SSSS(1,2)=SSSS(2,1)
      SSSS(1,3)=SSSS(3,1)
      SSSS(2,3)=SSSS(3,2)
C
C     FABRIC-BASED COMPLIANCE TENSOR CCCC
C 
      CCCC(1,1)=1.0D0/(E0*(MM1**(2.0D0*LS))*RHO**KS)
      CCCC(2,2)=1.0D0/(E0*(MM2**(2.0D0*LS))*RHO**KS)
      CCCC(3,3)=1.0D0/(E0*(MM3**(2.0D0*LS))*RHO**KS)
      CCCC(4,4)=0.5D0/(MU0*(MM1**LS)*(MM2**LS)*RHO**KS)
      CCCC(5,5)=0.5D0/(MU0*(MM3**LS)*(MM1**LS)*RHO**KS)
      CCCC(6,6)=0.5D0/(MU0*(MM2**LS)*(MM3**LS)*RHO**KS)
      CCCC(2,1)=-V0/(E0*(MM1**LS)*(MM2**LS)*RHO**KS)
      CCCC(3,1)=-V0/(E0*(MM1**LS)*(MM3**LS)*RHO**KS)
      CCCC(3,2)=-V0/(E0*(MM2**LS)*(MM3**LS)*RHO**KS)
      CCCC(1,2)=CCCC(2,1)
      CCCC(1,3)=CCCC(3,1)
      CCCC(2,3)=CCCC(3,2)
C
C     FABRIC-BASED QUADRIC FOURTH ORDER TENSOR DDDD
C 
      S0=(SIGD0P+SIGD0N)/2.0D0/SIGD0P/SIGD0N
C
      DDDD(1,1)=S0**2/(RHO**PP*MM1**(2.0D0*QQ))**2
      DDDD(2,2)=S0**2/(RHO**PP*MM2**(2.0D0*QQ))**2
      DDDD(3,3)=S0**2/(RHO**PP*MM3**(2.0D0*QQ))**2
      DDDD(1,2)=-(CHID0*(MM1/MM2)**(2.0D0*QQ))
     1                              *S0**2/(RHO**PP*MM1**(2.0D0*QQ))**2
      DDDD(1,3)=-(CHID0*(MM1/MM3)**(2.0D0*QQ))
     1                              *S0**2/(RHO**PP*MM1**(2.0D0*QQ))**2
      DDDD(2,3)=-(CHID0*(MM2/MM3)**(2.0D0*QQ))
     1                              *S0**2/(RHO**PP*MM2**(2.0D0*QQ))**2
      DDDD(2,1)=DDDD(1,2)
      DDDD(3,1)=DDDD(1,3)
      DDDD(3,2)=DDDD(2,3)
      DDDD(4,4)=0.5D0/((TAUD0*RHO**PP*(MM1*MM2)**QQ)**2)
      DDDD(5,5)=0.5D0/((TAUD0*RHO**PP*(MM1*MM3)**QQ)**2)
      DDDD(6,6)=0.5D0/((TAUD0*RHO**PP*(MM2*MM3)**QQ)**2)
C 
C     FABRIC-BASED QUADRIC SECOND ORDER TENSOR DD
C
      DD(1)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
     1                                   /(RHO**PP*MM1**(2.0D0*QQ))
      DD(2)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
     1                                   /(RHO**PP*MM2**(2.0D0*QQ))
      DD(3)=-(SIGD0P-SIGD0N)/2.0D0/SIGD0P/SIGD0N
     1                                   /(RHO**PP*MM3**(2.0D0*QQ))
      DD(4)=0.0D0
      DD(5)=0.0D0
      DD(6)=0.0D0
C     __________________________________________________________________
C
C     RECOVER STATE VARIABLES
C 
      ETOT1=STRAN+DSTRAN
      ETOT0=STRAN
C 
C    SDV 1-6: TOTAL STRESS TENSOR 
C    SDV 7: CUMULATED PLASTIC STRAIN
C    SDV 8: SCALAR DAMAGAE VARIABLE
C    SDV 9-14: PLASTIC STRAIN VECTOR
C    SDV 15-20: NOMINAL STRESS VECTOR
C    SDV 21-26: DENSIFICATION STRESS VECTOR
C    SDV 27: ORIGINAL BVTV
C    SDV 28: UPDATED BVTV 

   
      KAPPA0=STATEV(7)

      IF (KAPPA0<0.0D0) THEN
        KAPPA0=0.0D0
      ENDIF 
C
C     RECOVER AND ROTATE PLASTIC STRAIN 
C 
      CALL ROTSIG(STATEV( 9),DROT,EPLAS0,2,NDI,NSHR)
C
C     UPDATE BVTV
C
      DETF0 =  KDET(DFGRD0)
C 
      IF (RHO/DETF0 .GE. 1.0D0) THEN
      STATEV(28) = 1.0D0
      ELSE
      STATEV(28)=RHO/DETF0 
      ENDIF
C 
C     CONVERT INITIAL STRAINS TO VOITH-MANDL NOTATION
C 

      DO K1=4,6
         ETOT1(K1)=ETOT1(K1)/DSQRT(2.0D0)
         ETOT0(K1)=ETOT0(K1)/DSQRT(2.0D0)
         EPLAS0(K1)=EPLAS0(K1)/DSQRT(2.0D0)
      END DO
C
C     OVERNONLOCAL KAPPA AT THE BEGINNING OF THE INCREMENT
C
      KHAT1=XM*KAPPABAR+(1.0D0-XM)*KAPPA0
C
      IF (KHAT1<0.0D0) THEN
        KHAT1=0.0D0
      ENDIF  
C
C     STRESS AT THE BEGINNING OF THE CURRENT INCREMENT
C 
      SS0=(1.0D0-DAM(KHAT1,KONSTD,CRITD))*MATMUL(SSSS,ETOT0-EPLAS0)
C
C     ELASTIC EFFECTIVE TRIAL STRESS
C 
      STR=MATMUL(SSSS,ETOT1-EPLAS0)
C 
C     YIELD CRITERION WITH TRIAL STRESS
C 
      RAD=RADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA0)
      DRAD=DRADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA0)
      DDS=MATMUL(DDDD,STR)
      SDDS=DABS(DOT_PRODUCT(STR,DDS))
C 
      YSTR=DSQRT(SDDS)+DOT_PRODUCT(DD,STR)-RAD      
C     __________________________________________________________________
C
C     ELASTIC CASE
C     __________________________________________________________________
C 
      IF (YSTR<=TOL) THEN
C
C       UPDATE STATE VARIABLES
C    
        KAPPA1=KAPPA0
        EPLAS1=EPLAS0 
C
C       ELASTIC STRESS UPDATE
C
        SSEFF=STR
C 
        SS1=(1.0D0-DAM(KHAT1,KONSTD,CRITD))*STR
C
C       ELASTIC JACOBIAN
C 
        TANM=(1.0D0-DAM(KHAT1,KONSTD,CRITD))*SSSS        
C     __________________________________________________________________
C
C     INELASTIC CASE
C     __________________________________________________________________ 
C 
      ELSE IF (YSTR>TOL) THEN
C    
        ITER=0
        EPLAS1=EPLAS0
        DKAPPA1=0.0D0
        KAPPA1=KAPPA0+DKAPPA1
        SS1=STR                
C 
        RAD=RADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
        DRAD=DRADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
C 
        DDS=MATMUL(DDDD,SS1)
        SDDS=DABS(DOT_PRODUCT(SS1,DDS))
C
        DSY=1.0D0/DSQRT(SDDS)*DDS+DD
        DDSY=-1.0D0*(SDDS)**(-1.5D0)*VECDYAD(DDS,DDS)
     1                                          +1.0D0/DSQRT(SDDS)*DDDD
C
        HI=VECNORM(DSY)
        NP=DSY/HI
C 
        YS=DSQRT(SDDS)+DOT_PRODUCT(DD,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1)
        RR=MATMUL(CCCC,STR-SS1)-DKAPPA1*NP
C   
        ABSY=DABS(YS)
        NORMRR=VECNORM(RR)
        DDK1=0.0D0         
C   
C     __________________________________________________________________
C
C         NEWTON CLOSEST POINT PROJECTION W/O LINE SEARCH
C     __________________________________________________________________ 
C
C   
        DO WHILE ((NORMRR>TOL.OR.ABSY>TOL).AND.ITER<=10)
C 
          ITER=ITER+1 
C 
          SSI=SS1
          DKAPPAI=DKAPPA1
C 
          DHDS=1.0D0/DSQRT(DOT_PRODUCT(DSY,DSY))*MATMUL(DDSY,DSY)
          DHDK=0.0D0
          DYDS=DSY
          DYDK=-DRAD+VDYDK(VISCFL,ETA,MM,DTIME,DKAPPAI,DHDK)
          DNPDS=(DDSY*HI-VECDYAD(DSY,DHDS))/HI**2
          DNPDK=0.0D0
C
          DRRDS=-CCCC-DKAPPAI*DNPDS
          DRRDK=-NP
C 
          CALL MIGS(-DRRDS,6,SSSA)
C 
          DDK1=-(YS/HI+DOT_PRODUCT(NP,MATMUL(SSSA,RR)))
     1           /(DOT_PRODUCT(NP,MATMUL(SSSA,DRRDK))
     2          +DYDK/HI)
C 
          DSS1=MATMUL(SSSA,(RR+DRRDK*DDK1))
C         EFFECTIVE STRESS UPDATE 
          SS1=SSI+DSS1
C         CUMULATED PLASTIC STRAIN UPDATE
          DKAPPA1=DKAPPAI+DDK1
C 
C         IF DKAPPA1 BECOMES SMALLER THAN 0 AND THEREFORE INADMISSIBLE,
C         RESTART THE NEWTON SCHEME WITH A DIFFERENT STARTING POINT
C 
          IF (DKAPPA1<0.0D0) THEN
            SS1=STR
            DKAPPA1=0.0D0
          END IF
C 
          KAPPA1=KAPPA0+DKAPPA1
C
C         CHECK RESISUAL AND YIELD CRITERION AT I+1 FOR ITERATION BREAK
C 
          RAD=RADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
          DRAD=DRADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
          DDS=MATMUL(DDDD,SS1)
          SDDS=DABS(DOT_PRODUCT(SS1,DDS))
C
          DSY=1.0D0/DSQRT(SDDS)*DDS+DD
          DDSY=-1.0D0*(SDDS)**(-1.5D0)*VECDYAD(DDS,DDS)
     1                                          +1.0D0/DSQRT(SDDS)*DDDD
C
          HI=VECNORM(DSY)
          NP=DSY/HI
C 
          YS=DSQRT(SDDS)+DOT_PRODUCT(DD,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1)
          RR=MATMUL(CCCC,STR-SS1)-DKAPPA1*NP
C 
          NORMRR=VECNORM(RR)
          ABSY=DABS(YS)
C 
        END DO         
C     __________________________________________________________________
C
C         PRIMAL CPPA FOR GLOBAL CONVERGENCE
C     __________________________________________________________________ 
C
        IF (ITER.GT.10.AND.(NORMRR.GT.TOL.OR.ABSY.GT.TOL)) THEN 
C
          ITER=0
          EPLAS1=EPLAS0
          DKAPPA1=0.0D0
          KAPPA1=KAPPA0+DKAPPA1
          SS1=STR
C 
          RAD=RADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
          DRAD=DRADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
C 
          DDS=MATMUL(DDDD,SS1)
          SDDS=DOT_PRODUCT(SS1,DDS)
C
          DSY=1.0D0/DSQRT(SDDS)*DDS+DD
          DDSY=-1.0D0*(SDDS)**(-1.5D0)*VECDYAD(DDS,DDS)
     1                                          +1.0D0/DSQRT(SDDS)*DDDD
C
          HI=VECNORM(DSY)
          NP=DSY/HI
C 
          YS=DSQRT(SDDS)+DOT_PRODUCT(DD,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1)
          RR=MATMUL(CCCC,STR-SS1)-DKAPPA1*NP
C   
          ABSY=DABS(YS)
          NORMRR=VECNORM(RR)
C
          DO K1 = 1,6
            RRI(K1) = RR(K1)
          ENDDO
            RRI(7)=YS
C
          DO WHILE ((NORMRR>TOL.OR.ABSY>TOL).AND.ITER<=MAXITER)
C 
            ITER=ITER+1 
C 
            SSI=SS1
            DKAPPAI=DKAPPA1
C 
            DHDS=1.0D0/DSQRT(DOT_PRODUCT(DSY,DSY))*MATMUL(DDSY,DSY)
            DHDK=0.0D0
            DYDS=DSY
            DYDK=-DRAD+VDYDK(VISCFL,ETA,MM,DTIME,DKAPPAI,DHDK)
            DNPDS=(DDSY*HI-VECDYAD(DSY,DHDS))/HI**2
            DNPDK=0.0D0
C
            DRRDS=-CCCC-DKAPPAI*DNPDS
            DRRDK=-NP
C 
C           BUILD SYSTEM RESIDUAL VECTOR
C
            DO K1 = 1,6
              RRR(K1) = RR(K1)
            ENDDO
            RRR(7)=YS
C
            J11=DRRDS
            J22=DYDK
            J12=DRRDK
            J21=DYDS
C
C           BUILD SYSTEM JACOBIAN
C
            DO K1 = 1,6
              DO K2 = 1,6
                JJJ(K1,K2) = J11(K1,K2)
              ENDDO
              JJJ(7,K1)=J21(K1)
              JJJ(K1,7)=J12(K1)
            ENDDO
            JJJ(7,7)=J22
C
C           INVERT SYSTEM JACOBIAN
C
            CALL MIGS(JJJ,7,INVJ)
C
            AUX=0.0D0
            IF (DKAPPA1.EQ.0.0D0) THEN
              AUX=DOT_PRODUCT(NP,(SS1-STR))
            END IF
C
C           DETERMINE SYSTEM UPDATES
C
            IF (AUX.LE.0.0D0) THEN
C
              FLAG=1
C
              DDD=MATMUL(-INVJ,RRR)
C
            ELSE
C
              FLAG=0
C
              DDJ=MATMUL(INVJ,TRANSPOSE(INVJ))
              DO K1 = 1,6
                DDJ(7,K1)=0.0D0
                DDJ(K1,7)=0.0D0
              ENDDO
C
              DDD=MATMUL(-MATMUL(DDJ,TRANSPOSE(JJJ)),RRR)
C
            END IF  
C
C           RECOVER STRESS AND KAPPA UPDATE
C
            DO K1 = 1,6
              DSS1(K1)=DDD(K1)
            ENDDO
            DDK1=DDD(7)            
C 
            SS1=SSI+DSS1
            DKAPPA1=DKAPPAI+DDK1
C
            DO K1 = 1,6
              XXI(K1)=SS1(K1)
            ENDDO
            XXI(7)=DKAPPA1
C 
C           ENFORCE CONSTRAIN DKAPPA >= 0.0D0
C
            IF (DKAPPA1<0.0D0) THEN
              DKAPPA1=0.0D0
            END IF
C 
            KAPPA1=KAPPA0+DKAPPA1
C
C           CHECK RESIDUAL AND YIELD CRITERION AT I+1 FOR ITERATION BREAK
C 
            RAD=RADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
            DRAD=DRADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
            DDS=MATMUL(DDDD,SS1)
            SDDS=DOT_PRODUCT(SS1,DDS)
C
            DSY=1.0D0/DSQRT(SDDS)*DDS+DD
            DDSY=-1.0D0*(SDDS)**(-1.5D0)*VECDYAD(DDS,DDS)
     1                                          +1.0D0/DSQRT(SDDS)*DDDD
C
            HI=VECNORM(DSY)
            NP=DSY/HI
C 
C           LINE SEARCH MERIT FUNCTION AND DERIVATIVE OF ITERATION I
C
            MKI=0.5D0*(DOT_PRODUCT(RR,RR)+YS**2)
C
            IF (FLAG.EQ.1) THEN
              DMK=-2.0D0*MKI
            ELSE
              DMK=DOT_PRODUCT(RRR,MATMUL(JJJ,DDD))
            END IF
C           
C           RESIDUAL AND LINE SEARCH MERIT FUNCTION OF ITERATION I+1
C     
            YS=DSQRT(SDDS)+DOT_PRODUCT(DD,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1)
            RR=MATMUL(CCCC,STR-SS1)-DKAPPA1*NP
C
            DO K1 = 1,6
              RRR(K1) = RR(K1)
            ENDDO
            RRR(7)=YS
C
            MK1=0.5D0*(DOT_PRODUCT(RR,RR)+YS**2)
C
C           LINE SEARCH ALGORITHM FOR CONSTRAINED PROBLEMS (ARMERO 2002)
C
            IF (FLAG.EQ.1.AND.DKAPPA1.GE.0.0D0) THEN
              UPLIM=(1.0D0-2.0D0*BETA*ALPHA)*MKI
            ELSE
              UPLIM=MKI+BETA*DOT_PRODUCT(RRR,MATMUL(JJJ,XX1-XXI))
            END IF
C
            IF (MK1.GT.UPLIM) THEN
C
              ITERL=0
              ALPHA=1.0D0
              XX1=XXI
C
              DO WHILE (MK1.GT.UPLIM.AND.ALPHA.GE.BETA.AND.ITERL
     +                  .LT.20)
C
                ITERL=ITERL+1
C
                ALPHA1=ETAL*ALPHA
                ALPHA2=-ALPHA**2*DMK/2.0D0/(MK1-MKI-ALPHA*DMK)
C
                IF (ALPHA1.GE.ALPHA2) THEN
                  ALPHA=ALPHA1
                ELSE
                  ALPHA=ALPHA2
                END IF
C
                DKAPPA1=DKAPPAI+ALPHA*DDK1
C
                IF (DKAPPA1<0.0D0) THEN
                  DKAPPA1=0.0D0
                END IF

                KAPPA1=KAPPA0+DKAPPA1
                SS1=SSI+ALPHA*DSS1
C
                DO K1 = 1,6
                  XX1(K1)=SS1(K1)
                ENDDO
                XX1(7)=DKAPPA1
C
                RAD=RADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
                DDS=MATMUL(DDDD,SS1)
                SDDS=DOT_PRODUCT(SS1,DDS)
                DSY=1.0D0/DSQRT(SDDS)*DDS+DD
                HI=VECNORM(DSY)
                NP=DSY/HI
C   
                YS=DSQRT(SDDS)+DOT_PRODUCT(DD,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1)
                RR=MATMUL(CCCC,STR-SS1)-DKAPPA1*NP
C
                DO K1 = 1,6
                  RRR(K1) = RR(K1)
                ENDDO
                RRR(7)=YS
C
                MK1=0.5D0*(DOT_PRODUCT(RR,RR)+YS**2)
C
                IF (FLAG.EQ.1.AND.DKAPPA1.GE.0.0D0) THEN
                  UPLIM=(1.0D0-2.0D0*BETA*ALPHA)*MKI
                ELSE
                  UPLIM=MKI+BETA*DOT_PRODUCT(RRI,MATMUL(JJJ,XX1-XXI))
                END IF
C       
              END DO
C

              RAD=RADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
              DRAD=DRADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,KAPPA1)
              DDS=MATMUL(DDDD,SS1)
              SDDS=DOT_PRODUCT(SS1,DDS)
C
              DSY=1.0D0/DSQRT(SDDS)*DDS+DD
              DDSY=-1.0D0*(SDDS)**(-1.5D0)*VECDYAD(DDS,DDS)
     1                                          +1.0D0/DSQRT(SDDS)*DDDD
C
              HI=VECNORM(DSY)
              NP=DSY/HI
C         
              YS=DSQRT(SDDS)+DOT_PRODUCT(DD,SS1)-RAD
     1                           +VISCY(VISCFL,ETA,MM,DTIME,DKAPPA1)
              RR=MATMUL(CCCC,STR-SS1)-DKAPPA1*NP
C
              DO K1 = 1,6
                RRI(K1) = RR(K1)
              ENDDO
              RRI(7)=YS
C
            END IF
C 
            NORMRR=VECNORM(RR)
            ABSY=DABS(YS)
C 
          END DO
        END IF         
C 
        DHDS=1.0D0/DSQRT(DOT_PRODUCT(DSY,DSY))*MATMUL(DDSY,DSY)
        DHDK=0.0D0
        DYDS=DSY
        DYDK=-DRAD+VDYDK(VISCFL,ETA,MM,DTIME,DKAPPA1,DHDK)
        DNPDS=(DDSY*HI-VECDYAD(DSY,DHDS))/HI**2
        DNPDK=0.0D0
C
        DRRDS=-CCCC-DKAPPA1*DNPDS
        DRRDK=-NP
C 
        CALL MIGS(-DRRDS,6,SSSA)
C
C       DKDE FOR NONLOCAL UEL
C
        IF(KAPPA1-KAPPA0>0.0D0) THEN
          DKDE=-MATMUL(NP,SSSA)/(DOT_PRODUCT(NP,MATMUL(SSSA,DRRDK))
     1      +DYDK/VECNORM(DYDS))
        ENDIF
C
C       FINAL OVERNONLOCAL KAPPA
C
        KHAT1=XM*KAPPABAR+(1.0D0-XM)*KAPPA1
C        
        IF (KHAT1<0.0D0) THEN
          KHAT1=0.0D0
        ENDIF 
C
C       DDDK FOR NONLOCAL UEL
C
        DDDK=0.0D0
        IF(DAM(KHAT1,KONSTD,CRITD)-STATEV(8)>0.0D0) THEN
          DDDK=DDAM(KHAT1,KONSTD,CRITD)
        ENDIF
C
C       FINAL PLASTIC STRAIN
C 
        EPLAS1=ETOT1-MATMUL(CCCC,SS1)
C
C       FINAL ELASTOPLASTIC EFFECTIVE STRESS
C
        SSEFF=SS1
C
C       FINAL TOTAL ELASTOPLASTIC STRESS
C
        SS1=SSEFF*(1.0D0-DAM(KHAT1,KONSTD,CRITD))
C 
C       TANGENT STIFFNESS MATRIX
C
        TANM=(SSSA-MATMUL(MATMUL(SSSA,VECDYAD(DRRDK,NP)),SSSA)
     1        /(DOT_PRODUCT(NP,MATMUL(SSSA,DRRDK))+DYDK/VECNORM(DYDS)))
     2                                 *(1.0D0-DAM(KHAT1,KONSTD,CRITD))
     3                             -DDDK*(1.0D0-XM)*VECDYAD(SSEFF,DKDE)
C 
      END IF
C
C     CHECK FOR CONVERGENCE OF BACK PROJECTION ALGORITHM
C 
      IF (ABSY>TOL.AND.ITER>MAXITER) THEN
        PNEWDT=0.5
        KAPPA1=KAPPA0
        EPLAS1=EPLAS0
        KHAT1=XM*KAPPABAR+(1.0D0-XM)*KAPPA1
        IF (KHAT1<0.0D0) THEN
          KHAT1=0.0D0
        ENDIF 
        SS1=STR*(1.0D0-DAM(KHAT1,KONSTD,CRITD))
        SSEFF=STR
        TANM=(1.0D0-DAM(KHAT1,KONSTD,CRITD))*SSSS
      END IF
CC
      DO K1 = 1,6
        STATEV(14+K1) = SS1(K1)
      ENDDO
C
C
C    SDV 1-6: TOTAL STRESS TENSOR 
C    SDV 7: CUMULATED PLASTIC STRAIN
C    SDV 8: SCALAR DAMAGAE VARIABLE
C    SDV 9-14: PLASTIC STRAIN VECTOR
C    SDV 15-20: NOMINAL STRESS VECTOR
C    SDV 21-26: DENSIFICATION STRESS VECTOR
C    SDV 27: ORIGINAL BVTV
C    SDV 28: UPDATED BVTV 
C     __________________________________________________________________
C
C     DENSIFICATION ROUTINE          
C     __________________________________________________________________
C 
      IF (DENSFL.EQ.1) THEN
C     __________________________________________________________________
C
C     CALCULATE THE DENSIFICATION STRESS AND TANGENT           
C     __________________________________________________________________
C 
        TRACEEN = ETOT1(1)+ETOT1(2)+ETOT1(3)
C 
        CRITERION = TRACEEN-ECRIT
C 
        IF (CRITERION .LE. 0.0D0) THEN
C
C     SET THE NONLOCAL SCALE LENGTH TO ZERO
C 
        GAMMAL = GAMMAL0*(RHO**RL)
        GAMMAP = GAMMAP0*(RHO**RP)
C 
          DO K1=1,3
            DO K2=1,3
              SDNST(K1,K2) = (GAMMAL*CRITERION+GAMMAP*
     1            CRITERION**(POWERDNS-1.0D0))*XIDEN(K1,K2)
            ENDDO
          ENDDO
C     __________________________________________________________________
C
C     UPDATING THE NOMINAL STRESS TENSOR BY  
C     ADDING THE  DENSIFICATION STRESS     
C     __________________________________________________________________
C 
          DO K1 =1,3
            SS1(K1)=SS1(K1)+SDNST(K1,K1)
            SDNS(K1)=SDNST(K1,K1)
          ENDDO
C 
          SDNS(4)=SDNST(1,2)
          SDNS(5)=SDNST(1,3)
          SDNS(6)=SDNST(2,3)
C 
          SS1(4)=SS1(4)+SDNST(1,2)*DSQRT(2.0D0)
          SS1(5)=SS1(5)+SDNST(1,3)*DSQRT(2.0D0)
          SS1(6)=SS1(6)+SDNST(2,3)*DSQRT(2.0D0)
C
C     __________________________________________________________________
C
C     UPDATING THE NOMINAL JACOBIAN 
C     (ADDING THE DENSIFICATOR TANGENT STIFFNESS)     
C     __________________________________________________________________
C 
          XDENSSTIFF1 = (GAMMAL+GAMMAP*(POWERDNS-1.0D0)*
     1              CRITERION**(POWERDNS-2.0D0))
C 
          TANGDENS=XDENSSTIFF1*VECDYAD(XIDENV,XIDENV) 
C 
          TANM=TANM+TANGDENS 
C 
        ENDIF
C 
C     __________________________________________________________________
C
C     END OF DENSIFICATION ROUTINE               
C     __________________________________________________________________
C 
        DO K1 = 1,6
          STATEV(20+K1) = SDNS(K1)
        ENDDO
C
      ENDIF
C 
C     __________________________________________________________________
C
C     RETURN VARIABLES TO ABAQUS 
C     __________________________________________________________________
C
C     CONVERT TANGENT STIFFNESS OPERATOR MATRIX TO ABAQUS CONVENTION 
C 
      DO K1=4,6
        DO K2=4,6
          TANM(K1,K2)=TANM(K1,K2)/2.0D0
          TANM(K1-3,K2)=TANM(K1-3,K2)/DSQRT(2.0D0)
          TANM(K1,K2-3)=TANM(K1,K2-3)/DSQRT(2.0D0)
        END DO
      END DO
C     __________________________________________________________________
C
C     CONVERT STRESSES AND STRAINS TO ABAQUS CONVENTION 
C 
      DO K1=4,6
        SS1(K1)=SS1(K1)/DSQRT(2.0D0)
        EPLAS1(K1)=EPLAS1(K1)*DSQRT(2.0D0)
        EPLAS0(K1)=EPLAS0(K1)*DSQRT(2.0D0)
      END DO 
C     __________________________________________________________________     
C
C     UPDATE OF FIELD VARIABLES
C 
C     TOTAL STRESS TENSOR
C 
      STRESS=SS1
C
      DO K1 = 1,6
        STATEV(K1) = SS1(K1)
      ENDDO
C    
C     TANGENT STIFFNESS OPERATOR 
C 
      DDSDDE=TANM
C
C     STRAIN ENERGY
C 
C      SSE=SSE+DOT_PRODUCT((SS0+SS1)/2.0D0,DSTRAN)
C
C    SDV 1-6: TOTAL STRESS TENSOR 
C    SDV 7: CUMULATED PLASTIC STRAIN
C    SDV 8: SCALAR DAMAGAE VARIABLE
C    SDV 9-14: PLASTIC STRAIN VECTOR
C    SDV 15-20: NOMINAL STRESS VECTOR
C    SDV 21-26: DENSIFICATION STRESS VECTOR
C    SDV 27: ORIGINAL BVTV
C    SDV 28: UPDATED BVTV   
C
C     PLASTIC STRAIN TENSOR
      DO K1=1,6
        STATEV(8+K1)=EPLAS1(K1)
      END DO
C
C     CUMULATED PLASTIC STRAIN      
      STATEV(7)=KAPPA1
C     DAMAGE
      STATEV(8)=DAM(KHAT1,KONSTD,CRITD)
C     BV/TV
      STATEV(27)=RHO
C          
      RETURN
      END
C
C    ************************************ END OF THE UMAT SUBROUTINE *******************************************
C     __________________________________________________________________
C
C     MATERIAL MODEL FUNCTIONS
C     __________________________________________________________________
C
C     DAMAGE FUNCTION DAM(k)
C 
      DOUBLE PRECISION FUNCTION DAM(KAPPA,KONSTD,CRITD)
      IMPLICIT NONE
      DOUBLE PRECISION KAPPA,KONSTD,CRITD
C     MEAN KONSTK OF WOLFRAM (JBIOMECH 2011) FOR COMPRESSION AND 
C     TENSION, AXIAL AND TRANSVERSE: 8.0075, CRITD=0.85
      DAM=CRITD*(1.0D0-DEXP(-KONSTD*KAPPA))
      RETURN
      END
C
C     DERIVATIVE OF DAMAGE FUNCTION dDAM/dk
C 
      DOUBLE PRECISION FUNCTION DDAM(KAPPA,KONSTD,CRITD)
      IMPLICIT NONE
      DOUBLE PRECISION KAPPA,KONSTD,CRITD
C     MEAN KONSTK OF WOLFRAM (JBIOMECH 2011) FOR COMPRESSION AND 
C     TENSION, AXIAL AND TRANSVERSE: 8.0075, CRITD=0.85
      DDAM=CRITD*KONSTD*DEXP(-KONSTD*KAPPA)
      RETURN
      END
C
C     POSTYIELD FUNCTION r(k)
C 
      DOUBLE PRECISION FUNCTION RADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,
     +                                   KAPPA)
      IMPLICIT NONE
      DOUBLE PRECISION EXPS,RDY,KMAX,PDY,KAPPA,RDY2
      INTEGER PYFL
C 
C     PERFECT PLASTICITY
      IF (PYFL.EQ.0) THEN
        RADK=1.0D0
C     LINEAR HARDENING
      ELSEIF (PYFL.EQ.1) THEN
        RADK=1.0D0+EXPS*KAPPA
C     EXPONENTIAL HARDENING
      ELSEIF (PYFL.EQ.2) THEN
        RADK=1.0D0+(RDY-1.0D0)*(1.0D0-DEXP(-EXPS*KAPPA))
C     QUADRATIC HARDENING
      ELSEIF (PYFL.EQ.3) THEN
        RADK=RDY2+(PDY-RDY2)*(1.0D0-DEXP(-EXPS*KAPPA))
      ENDIF
C
      RETURN
      END
C
C     DERIVATIVE OF POSTYIELD FUNCTION dr/dk
C 
      DOUBLE PRECISION FUNCTION DRADK(PYFL,EXPS,KMAX,RDY,RDY2,PDY,
     +                                    KAPPA)
      IMPLICIT NONE
      DOUBLE PRECISION EXPS,RDY,KMAX,PDY,KAPPA,RDY2
      INTEGER PYFL
C
C     PERFECT PLASTICITY
      IF (PYFL.EQ.0) THEN
        DRADK=0.0D0
C     LINEAR HARDENING
      ELSEIF (PYFL.EQ.1) THEN
        DRADK=EXPS
C     EXPONENTIAL HARDENING
      ELSEIF (PYFL.EQ.2) THEN
        DRADK=(RDY-1.0D0)*EXPS*DEXP(-EXPS*KAPPA)  
C     QUADRATIC HARDENING
      ELSEIF (PYFL.EQ.3) THEN
        DRADK=(PDY-RDY2)*EXPS*DEXP(-EXPS*KAPPA)
      ENDIF
C 
      RETURN
      END
C
C     VISCOSITY FUNCTION
C
      DOUBLE PRECISION FUNCTION VISCY(VISCFL,ETA,MM,DTIME,DKAPPA)
      IMPLICIT NONE
      DOUBLE PRECISION ETA,MM,DTIME,DKAPPA,HI
      INTEGER VISCFL
C     RATE-INDEPENDENT
      IF (VISCFL.EQ.0) THEN
        VISCY=0.0D0
C     LINEAR FLOW RULE
      ELSEIF (VISCFL.EQ.1) THEN
        VISCY=-ETA/DTIME*DKAPPA
C     EXPONENTIAL FLOW RULE
      ELSEIF (VISCFL.EQ.2) THEN
        VISCY=-LOG(1.0D0+ETA/DTIME*DKAPPA)/MM
C     LOGARITHMIC FLOW RULE
      ELSEIF (VISCFL.EQ.3) THEN
        VISCY=-(EXP(ETA/DTIME*DKAPPA)-1.0D0)/MM
C     POLYNOMIAL FLOW RULE
      ELSEIF (VISCFL.EQ.4) THEN
        VISCY=0.5D0*MM-DSQRT((MM**2)/4.0D0+ETA/DTIME*DKAPPA)
C     POWER LAW FLOW RULE
      ELSEIF (VISCFL.EQ.5) THEN
        VISCY=-(ETA/DTIME*DKAPPA)**(1.0D0/MM)
      ENDIF
      RETURN
      END
C
      DOUBLE PRECISION FUNCTION VDYDK(VISCFL,ETA,MM,DTIME,DKAPPA,
     +                                   DHDK)
      IMPLICIT NONE
      DOUBLE PRECISION ETA,MM,DTIME,DKAPPA,DHDK,HI
      INTEGER VISCFL
C     RATE-INDEPENDENT
      IF (VISCFL.EQ.0) THEN
        VDYDK=0.0D0
C     LINEAR FLOW RULE
      ELSEIF (VISCFL.EQ.1) THEN
        VDYDK=-ETA/DTIME
C     EXPONENTIAL FLOW RULE
      ELSEIF (VISCFL.EQ.2) THEN
        VDYDK=-ETA/DTIME/MM/(1.0D0+ETA/DTIME*DKAPPA)
C     LOGARITHMIC FLOW RULE
      ELSEIF (VISCFL.EQ.3) THEN
        VDYDK=-ETA/DTIME/MM*EXP(ETA/DTIME*DKAPPA)
C     POLYNOMIAL FLOW RULE
      ELSEIF (VISCFL.EQ.4) THEN
        VDYDK=-0.5D0*(ETA/DTIME)/DSQRT((MM**2)/4.0D0+ETA/DTIME*DKAPPA)
C     POWER LAW FLOW RULE
      ELSEIF (VISCFL.EQ.5) THEN
        VDYDK=-1.0D0/MM*DKAPPA**(1.0D0/MM-1.0)*ETA/DTIME
      ENDIF
      RETURN
      END
C     __________________________________________________________________
C 
C     MATHEMATICAL FUNCTIONS
C     __________________________________________________________________
C     
C     INTRINSIC FUNCTIONS:
C
C     MATMUL(AAAA,BBBB)
C     MULTIPLICATION MATRIX WITH MATRIX
C
C     MATMUL(AAAA,BB)
C     MULTIPLICATION MATRIX WITH VECTOR
C
C     DOT_PRODUCT(AA,BB)
C     SCALAR PRODUCT OF TWO VECTORS
C 
C     EXTERNAL FUNCTIONS:
C     _________________________________________________________________
C 
      FUNCTION VECDYAD(BB,CC)
      IMPLICIT NONE
C     DYADIC PRODUCT AB OF VECTORS BB AND CC WITH DIMENSION 6x1  
      DOUBLE PRECISION BB(6),CC(6)
      DOUBLE PRECISION VECDYAD(6,6)
      INTEGER I,J
C 
      VECDYAD=0.0D0
C 
      VECDYAD=SPREAD(BB,2,SIZE(CC))*SPREAD(CC,1,SIZE(BB))
C 
      RETURN
      END
C     _________________________________________________________________
C 
      DOUBLE PRECISION FUNCTION VECNORM(DD)
      IMPLICIT NONE
C     NORM OF VECTOR AA WITH DIMENSION 6x1
      DOUBLE PRECISION DD(6)
C 
      VECNORM=DSQRT(DOT_PRODUCT(DD,DD))
C 
      RETURN
      END
C     __________________________________________________________________ 

C
      DOUBLE PRECISION FUNCTION KDET(A)
      IMPLICIT NONE
      DOUBLE PRECISION A(3,3)

      KDET =    A(1,1)*A(2,2)*A(3,3) +
     +          A(1,2)*A(2,3)*A(3,1) +
     +          A(1,3)*A(2,1)*A(3,2) -
     +          A(1,3)*A(2,2)*A(3,1) -
     +          A(1,2)*A(2,1)*A(3,3) -
     +          A(1,1)*A(2,3)*A(3,2)

      RETURN
      END
